### ISSUE TITLE
Support Assembly Redirection

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#1]
Originally filed December 08 2021 by Rolf Madsen on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/822)

Sometimes a newer version of a given dll needs to be used in place of an older one. This can give issues if the old one is being used by a plugin that is loaded before the plugin that needs to newer dll.

This issue has been seen with KS8400A and the Keysight Fixed Licensing dll.

- That sometimes 1.2.3 is incompatible with 1.2.2. I believe this has been the case for Newtonsoft.Json. So we cannot simply load the newest compatible version (our old behavior).
- Often the first loaded code is the one who gets to decide which dll is loaded. example: Editor.exe

Proposal:
```xml
<Files>
    <File>Dependencies/A.1.2.3/A.dll</file>
</Files>

<Files>
    <!-- we promise this assembly is as good as 1.2.3 -->
    <File Substitues="Dependencies/A.1.2.3/A.dll">Dependencies/A.1.2.4/A.dll</file>
</Files>
```

Given this package xml, we could also just delete A.1.2.3/A.dll when a substitute is detected. But then we'd also have to add it back when the package is uninstalled.

**Comment by alnlarsen** [comment]
I don't think this is necessary. This implementation is a pretty complicated solution to something we can currently solve with .OpenTapIgnore (and this solution is already used by other plugins)

If Plugin A needs to replace A.1.2.3 with A.1.2.4, it would simply ship "Dependencies/A.1.2.3/.OpenTapIgnore" which will force OpenTAP to resolve A.1.2.4 instead.

@AsgerIversen what do you think? Should we just close this?

**Comment by rmadsen-ks** [comment]
I think the current solution with using .OpenTapIgnore is an acceptable solution to this.
