### ISSUE TITLE
ComponentSettings.SetCurrent does not return errors

### ISSUE THREAD

**Issue by enes-ozturk** [opentap/opentap#1000]
**Describe the bug**

OpenTAP no longer throws exceptions in ComponentSettings.SetCurrent. We realized this when the runners didn't return any serialization errors in the response of `UploadComponentSettings()`. 

These errors typically happen if the packages on which the TapSettings/TapPlan file depends are not installed in that session/runner and are sent back as a response from methods such as `LoadTestPlanFromRepository()`.

**Comment by alnlarsen** [comment]
I looked into it, and it doesn't look like we've changed the behavior here in a while. @Denrask can you comment on this? It would be pretty simple for a plugin to check for serialization errors without changing OpenTAP behavior. 

I think it would be preferable if `SetCurrent` returned a list of errors, but I don't think we should change this behavior unless you can convince me this is a regression.

**Comment by alnlarsen** [comment]
I have determined that `SetCurrent` has only ever thrown exceptions in some circumstances. I think it's a shame that it has a `void` return type. The name is also not that descriptive.

I think instead we should add a new method, something like `SetFromXmlStream`, which returns an array of XmlErrors, and throws if the input is not valid XML.
