### ISSUE TITLE
Moving steps may cause Inputs to become corrupted

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1018]
1. Create a test plan with two If Verdict
2. The last step: Select the first step as input.
3. Swap the steps
4. The (now) first step, select None in the drop down.
5. swap the steps again
6. The seconds step: Note that the input is blank (not none)

This is caused because the input has two properties: property and step. 
When a step is deleted, any inputs referring to it are set to None.
When moving a step, it looses the context and the step is set to null, but then when it is inserted at the new position we use the step id to find to right step reference.
However, when explicitly setting the input, the property and step are set to null, but the Step ID is still set. When we then move the step the Step is set to something, while the property is still null, causing a corrupted Input configuration.

![image](https://user-images.githubusercontent.com/24250062/218949355-1eff80ca-1071-4428-9c7a-625ac49ae98b.png)

**Comment by jfaaborg** [comment]
Is this bug a regression ?

**Comment by alnlarsen** [comment]
It doesn't look like a regression.
