### ISSUE TITLE
`tap package install` offers to try a beta even though it does not exist

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1032]
**Describe the bug**

tap package install offers to try a beta even though it does not exist

**Environment (please complete the following information):**

 - OS :Windows 10
 - OpenTAP Version 9.20.0-rc.2
 - 
**To Reproduce**

1. Install Dotfuscator `tap package install Dotfuscator  -r "http://packages.opentap.keysight.com"`
2. Delete the Dotfuscator .tappackage from cache
3. Ensure there are no Dotfuscator beta available `tap package list Dotfuscator --version beta`
4. Reinstall `tap package install Dotfuscator` 

**Actual behavior**
It offers to try a beta even though it does not exist.
This happens only when 
- Dotfuscator is already installed
- Dotfuscator is not on the default repo for the command at step 4
- Dotfuscator package is not in cache

![image](https://user-images.githubusercontent.com/97734470/220844319-791805d9-309e-4a62-b127-3150461f78d9.png)

**Expected behavior**

`Package 'Dotfuscator' not found`

**Additional info**

Choosing `No` for trying a beta still seems to install the beta

**Comment by bogdan-achim** [comment]
Confirmed as fixed in v9.21.0-beta.10:

![image](https://user-images.githubusercontent.com/118886454/233373508-1f060a9d-d25b-4206-8c9b-d76baaa99bb0.png)
