### ISSUE TITLE
Stuck during dowgrade to an invalid version of OpenTAP

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1035]
**Describe the bug**

`tap package install OpenTAP` behaves differently than `tap package install OpenTAP --version 9.19.5` and both should install the same version

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.20.0-rc.2

**To Reproduce**

1. Install OpenTAP 9.20.0-rc.2
2. Install SDK 9.20.0-rc.2
3. Run `tap package install OpenTAP`

**Actual behavior**

CMD stuck nothing is displayed. Log: 
[SessionLog 2023-02-23 12-27-39.txt](https://github.com/opentap/opentap/files/10812552/SessionLog.2023-02-23.12-27-39.txt)

**Expected behavior**

Message that image cannot be resolved since SDK requires OpenTAP ^9.20.0-rc.2

**Additional context**

Add any other context about the problem here. Please also attach a log file from <InstallDir>\SessionLogs\ that shows the issue when possible/relevant.

**Comment by alnlarsen** [comment]
@sebastian-pop I was able to reproduce this, but I believe this is actually the "intended" behavior.

Since @rmadsen-ks improved the resolver, it appears to be stuck, but it is actually checking every possible configuration of `OpenTAP` and `SDK` to see if there is any combination that satisfies the requirements.

I left it running on my machine, and after 1 minute and 7 seconds, I got the following output: 

```
$ ./tap package install OpenTAP
Updates available for:
 - Keysight Licensing: 1.3.0+5ca24fcb -> 1.3.1+32de61e1
 - PathWave License Manager: 2.5.1+b6a9a8c2 -> 2.7.0+398d3a87
 - TUI: 1.0.0-beta.22+a7078ad3 -> 1.0.0+48ed6e30
Image configuration:
Could not resolve OpenTAP
  OpenTAP:
  Editor: ^9.19.1+26c29bbb
  Keysight Licensing: ^1.3.0+5ca24fcb
  OSIntegration: ^1.4.2+15f32a31
  SDK: ^9.20.0-rc.2+cdbbf647
  TUI: ^1.0.0-beta.22+a7078ad3
  WPF Controls: ^9.19.1+26c29bbb
  Keysight Fixed License Manager: ^1.4.1+e5816333
  PathWave License Manager: ^2.5.1+b6a9a8c2
This might be because of the following broken packages:
   Editor missing OpenTAP:^9.19.4+7959a308.
   Keysight Licensing missing OpenTAP:^9.17.4+ea67c63a.
   OSIntegration missing OpenTAP:^9.5.0+45ab79bc.
   SDK missing OpenTAP:^9.20.0-rc.2+cdbbf647.
   TUI missing OpenTAP:^9.18.3+fc9e60e0.
   WPF Controls missing OpenTAP:^9.19.4+7959a308.
```
