### ISSUE TITLE
Type menu annotations

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1037]
Currently we have member menu annotations. These are used for adding additional functionality for a setting, usually in the form of a context menu item.

For example, we have 'assign output' as a menu annotation.  These are currently widely supported. 

It would be nice to also have support for 'type' menu annotations. Instead of the functionality being available for a given setting, it would be the object itself that has it. Currently, this could be useful for:

- Exporting/Importing test plan settings as a CSV file (current feature in KS8400, it could be improved with this feature).
- Dynamic test step settings. Currently this has to be implemented by the right click menu of a property. Additing a context menu for the step itself or at least locating the functionality there would make more sense.

**Comment by sebastian-pop** [comment]
Will be tested in KS8400
