### ISSUE TITLE
Resolver error: can't install system-wide package from local .TapPackage

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1043]
I reproduced this in 9.20 RC and 9.19.5

I tried installing a system-wide package from a local .TapPackage file, but the resolver failed to find it (after correctly resolving the image). 

There are two workarounds:
1. Run the CLI action as admin
2. Copy the .TapPackage into the package cache

It seems to be related to elevation.

**Comment by sebastian-pop** [comment]
Verified on 9.21.0-beta.12

I cannot reproduce this issue before the fix.

The difference after the fix I found was that the `.tappackage` file is copied to the cache when trying to install it. On the previous version this happened only with an elevated CMD. Now it works without an elevated CMD
