### ISSUE TITLE
Package Create Bug: netstandard.dll added to Dependencies

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1048]
I am not sure when this was introduced, but using 9.19.5, OpenTAP sometimes puts netstandard.dll into Dependencies during package create:

'MyPlugin.dll' depends on 'netstandard' version '2.0.0.0'. Adding dependency to package, it was not found in any other packages.

**Comment by alnlarsen** [comment]
This is a regression from 9.18 to 9.19

**Comment by alnlarsen** [comment]
https://github.com/opentap/opentap/pull/791#issuecomment-1240346239

**Comment by alnlarsen** [comment]
Tangentially related to this issue, I had an informal discussion with @AsgerIversen some months ago about always bundling all package dependencies during `package create`. That way, it is no longer breaking for OpenTAP (or some other package) to stop shipping a dependency because that dependency would be shipped by its dependents anyway. The package manager and assembly resolver should already be capable of handling conflicts arising from this.

**Comment by rmadsen-ks** [comment]
This will be fixed by moving to .net 8. Besides that this has not shown to be an issue. Closing it for now.
