### ISSUE TITLE
Error resolving beta dependencies

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1051]
To reproduce:

`./tap image install "Runner:0.2.3,Keysight Connect:0.1.0"`
`./tap package install Runner --version 1.0.0-beta.9+c3da9897`

The resolution fails because Runner 1.0.0-beta.9+c3da9897 depends on "Keysight Connect ^0.2.0-beta", but for some reason our resolver doesn't check for Keysigth Connect prereleases. 

The resolution succeeds if I manually download Keysight Connect 0.2.0-beta and place it in my PackageCache folder. 

Note that this example will probably succeed soon because Keysight Connect 0.2.0 will be released.

**Comment by bogdan-achim** [comment]
Confirmed as fixed in version 9.21.0-beta.10

![image](https://user-images.githubusercontent.com/118886454/233371598-16a69487-8fe0-433b-ba4a-8bbcbf192b1a.png)
