### ISSUE TITLE
OpenTAP version does not show betas in SQLite saved run

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1059]
**Describe the bug**

These parameters are used in KS8500 for saving run parameters

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.20.2

**To Reproduce**

1. Have KS8400 9.20.0-RC.1 installed
2. Have OpenTAP 9.20.2-beta.1 installed
3. Add an SQLite result listener
4. Run a Delay step
5. Open Run Explorer
6. Add the column `Version.OpenTAP` and `Version.OpenTap.Plugins.BasicSteps` to the table

**Actual behavior**

OpenTAP version is displayed as 9.20.2.0

![image](https://user-images.githubusercontent.com/97734470/226365996-d1e2170e-b08c-4065-bb1e-6f98cd13b703.png)

**Expected behavior**

OpenTAP version should be 9.20.2-beta.1

**Additional context**

**Comment by alnlarsen** [comment]
From looking into the code this doesn't look like a bug. The stored result is the assembly version, and not the version of the plugin containing the assembly.

**Comment by sebastian-pop** [comment]
@alnlarsen fair enough. Closing this then
