### ISSUE TITLE
Package Manager won't load packages from paths starting with `//`

### ISSUE THREAD

**Issue by tboye-qblox** [opentap/opentap#1082]
**Describe the bug**

Package Manager won't load packages from paths starting with `//`

**Environment**

 - OS: Windows 11
 - OpenTAP Version: 9.20

**To Reproduce**

1. Add a network location in Windows: `\\<IP address>\<directory>` containing `.TapPackage` files
2. Add package location `\\<IP address>\<directory>` in Package Manager

**Actual behavior**

Package Manager reports: `Error: File package repository not found at file:///C:/<directory>`

**Expected behavior**

Packages are successfully loaded from the network location.

**Additional context**

OpenTAP 9.17 doesn't have this issue. It seemsit might be related to the following changes:
- https://github.com/opentap/opentap/pull/716/files
- https://github.com/opentap/opentap/pull/798/files

**Comment by Razvan-Muresan** [comment]
Verified using OpenTAP version 9.21.1-beta.8
