### ISSUE TITLE
'Tap package verify' command fails for OpenTAP: 'tap.exe' has non-matching checksum

### ISSUE THREAD

**Issue by bogdan-achim** [opentap/opentap#1083]
**Describe the bug**

Package verify fails for OpenTAP: 'tap.exe' has non-matching checksum

**Environment (please complete the following information):**

 - OS: Windows 10 x64
 - OpenTAP: 9.20.4

**To Reproduce**

1. Install OpenTAP
2. Open Command Prompt in the OpenTAP installation folder
3. Run "tap package verify OpenTAP" 

**Actual behavior**

The output returned is:

Package 'OpenTAP' not verified.
File 'tap.exe' has non-matching checksum

**Additional context**

![tap_package_verify](https://user-images.githubusercontent.com/118886454/230304977-17872d62-3883-49f0-8333-26cf8e7f6dec.png)

This issue also occurs on OpenTAP 9.18 & 9.19.

**Comment by sebastian-pop** [comment]
Implemented. Verified on 9.22,0-beta.43.

Related issue reported here: https://github.com/opentap/opentap/issues/1252
