### ISSUE TITLE
CliUserInputImplementation: Handle case when no TTY is connected

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1092]
When running in an environment with no stdin connected, the current implementation just hangs. We should detect if there is no stdin, and read from the stdin pipe.

I saw this exception in a GitHub pipeline: `InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
`

**Comment by rmadsen-ks** [comment]
Since this turned out to be harder than expected, we will move this to 9.23.

**Comment by alnlarsen** [comment]
The echo test should also work in powershell on windows

**Comment by Razvan-Muresan** [comment]
Verified on OpenTAP version 9.24.0-beta.34
