### ISSUE TITLE
Allow more flexibility in ordering of IStringConvertProviders

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1097]
Currently we have an IConvertible StringConvertProvider. This is normally fine, but since Pythonnet/PyObject has a pretty broken IConvertible implementation, it makes the object impossible to clone with the current system.

If we had a way to specify the order, then this could be done by checking PyObjectconvertProvider before ConvirtibleConvertProvider.
This could be done simply with an 'IOrderedStringConvertProviderPlugin that contains a single double property.

But maybe we could think of some more generic way of doing ordering in our plugins? something like double Order(ITypeData otherType). to specify where something comes relative to another plugin. or with an attribube like: [Before(Type)] .

This is needed in order to fix https://github.com/opentap/OpenTap.Python/issues/108

**Comment by sebastian-pop** [comment]
Cannot be tested by QA. There is a unit test for it
