### ISSUE TITLE
Signed and Strong named Assembly

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#11]
Originally filed March 05 2020 by kai sek lim on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/174)

Currently OpenTap.dll is signed without strong named. All our projects are signed with strong-named. In this case, we can't reference it in our project.

**Comment by rmadsen-ks** [comment]
Strong named assemblies are not checked in .net 5 and on. So we will not be supporting this usecase in the future.

See: https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies
