### ISSUE TITLE
Saving the logs to a new text file using "--log" breaks the Latest.txt log file on linux

### ISSUE THREAD

**Issue by bogdan-achim** [opentap/opentap#1107]
**Describe the bug**

Saving the logs to a new text file using "--log" breaks the Latest.txt log file

**Environment (please complete the following information):**

 - Ubuntu 20.04
 - OpenTAP 9.21.0-rc.2

**To Reproduce**

1. Open the Terminal in the OpenTAP installation folder
2. Run "tap package install Demonstration" and make sure the output is correct
3. Make sure the "Latest.txt" file exists in the SessionLogs folder and it can be opened
4. Run "tap package uninstall Demonstration --log ./SessionLogs/NewLogs.txt"
5. After the output appears, check the SessionLogs folder

**Actual behavior**

The "Latest.txt" file is broken

![Latest_log_file_is_broken_when_saving_log_to_different_file_with_--log_argument](https://user-images.githubusercontent.com/118886454/234353673-b84b24d9-5149-4e9c-a808-93eb1c59c80d.gif)

*Additional Notes**
This issue occurs when using the Uninstall, Download, Verify and Show commands.

**Comment by sebastian-pop** [comment]
Confirmed as fixed on 9.21.1-beta.8
