### ISSUE TITLE
Add Hash property to TestPlanReference steps

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1110]
When we run a test plan, we generate a Hash which is stored as a result.
This hash can be used to check if the test plan was changed between runs.

When a test plan uses TestPlanReference steps, this behavior is not always reliable.
It is possible to modify a referenced test plan without the main test plan being aware of that fact.

I suggest adding a Hash property to test plan references. That way, the hash of the parent test plan will change if any test plan it references has changed.

**Comment by sebastian-pop** [comment]
Implemented. Verified on 9.22.0-rc.1



![Image](https://github.com/opentap/opentap/assets/97734470/79c7395c-4db1-4ea8-a104-530137ea5d8f)
