### ISSUE TITLE
Add TestPlanRun / TestStepRun property: Status

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1117]
Currently, there is no reliable way to check if a teststep or testplan ran to completion, was aborted due to a break condition, or was aborted by the user. I think we should add a public status Enum to stepruns / planruns indicating which of the following is the case:

1. Finished normally
2. Was cancelled by the operator
3. Was cancelled due to a break condition

This status should be written to results etc.

**Comment by MikkoAla-Kojola** [comment]
Hello

I am hoping this feature would make it's way from backlog to some release? We would need the information of whether plan was fully run or not in one of our result listeners.

Cheers

Mikko

**Comment by bogdan-achim** [comment]
![image](https://github.com/opentap/opentap/assets/118886454/e89a2c69-5124-43b4-bf2e-6bbdc7f7f82f)

Verified in v9.24.0-rc.1. This works as intended
