### ISSUE TITLE
Make LockingPackageActions locking

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1122]
Currently, LockingPackageActions are only mutually exclusive amongst themselves. E.g. it is not possible to run two concurrent install operations. But it is possible to start e.g. a testplan while a locking package action is running. 

Package actions are typically locking because they need to write to the installation folder. An install action may fail if a test plan is started while it is writing the installation, and the test plan results may be invalid because the installation was partially modified or even corrupted.

I propose making all CLI actions wait for the lock on the installation folder, and release the lock immediately if it is not a locking package action.

**Comment by alnlarsen** [comment]
This should be moved to 9.22.0

**Comment by rmadsen-ks** [comment]
This will not be included in 9.22.  See my note here: https://github.com/opentap/opentap/pull/1165#pullrequestreview-1613099156

**Comment by rmadsen-ks** [comment]
We won't fix this. This feature will not be scoped to what is described here.
