### ISSUE TITLE
Add .exe and .tar files as assets to the Release Notes

### ISSUE THREAD

**Issue by bdirenzo-keysight** [opentap/opentap#1125]
Currently, we include the source, but I think we should include the installers as well, since there isn't a great way to archive/find old versions currently

![image](https://github.com/opentap/opentap/assets/78063177/3fb5878c-17ad-4fe3-aede-c09cf1701eb9)

**Comment by bdirenzo-keysight** [comment]
> Hi @bdirenzo-keysight
> 
> All installers from 9.20 and up are archived on the package repo:
> 
> https://packages.opentap.io/4.0/Objects/www/OpenTAP.exe?version=9.20.0&format=full
> 
> The version query argument can be replaced with any version specifier.
> 
> When you say `.tar` file, are you referring to the Linux installer? Since 9.20, we have also built a smartinstaller for Linux. I think we would prefer to promote that installer instead.
> 
> Would it be fine to include links to the appropriate version on the repository for a Linux and Windows installer instead of including them as assets?

@alnlarsen for people not that familiar I don't think it is that initiative to edit the URL. I understand the point though of not waiting to have the installers archived in multiple places though.

What if the release notes just had the link to the repo to that specific version? So we don't have to replicate storing the installers but at least make them a little easier to find.

And yes tar is not a requirement. The SmartInstaller version is fine for Linux.

**Comment by alnlarsen** [comment]
> @alnlarsen for people not that familiar I don't think it is that initiative to edit the URL. I understand the point though of not waiting to have the installers archived in multiple places though.

Maybe I was unclear earlier. I didn't mean to say that people should just edit the URL to get old versions. What I meant to say is that we are already archiving them, so we can go back to earlier releases and add the download links.

> What if the release notes just had the link to the repo to that specific version? So we don't have to replicate storing the installers but at least make them a little easier to find.

That's essentially what I was suggesting. It sounds like we're in agreement

**Comment by alnlarsen** [comment]
I added download links to the 9.21.0 release. Do you think this looks okay? If this is fine I will go back and add links to the 9.20.x releases

![image](https://github.com/opentap/opentap/assets/95965749/810a9cde-0471-4818-a998-8f4453ed69ec)

**Comment by rmadsen-ks** [comment]
Assets added to https://github.com/opentap/opentap/releases/tag/v9.22.2.
