### ISSUE TITLE
xmlns points to 404 page not found

### ISSUE THREAD

**Issue by kaushik-keysight** [opentap/opentap#1138]
**Describe the bug**

package.xml file contains xml namespace with `xmlns=http://opentap.io/schemas/package`
When clicked it shows a 404 page exception. Please restore this page.

![image](https://github.com/opentap/opentap/assets/102044729/db3051eb-8143-4ff9-ba36-54c499035270)

**Comment by rmadsen-ks** [comment]
@StefanHolst, can you help moving this to the appropriate issue tracker?

**Comment by StefanHolst** [comment]
https://gitlab.com/opentap-operations/homepage/-/issues/4
