### ISSUE TITLE
CI tests: Use SmartInstaller for regression tests instead of debug package

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1152]
We are currently running a regression testplan for Windows, Linux, and MacOS. The regression testplan is using the `OpenTap.Debug.TapPackage` build artifact for testing. The SmartInstaller we create resembles a real setup much more closely than the debug package we create, and SmartInstaller is now supported on Linux and Mac, which was not the case when the regression tests were initially created. We should change the regression tests to use the installers instead.

**Comment by rmadsen-ks** [comment]
After discussing with @alnlarsen, we have decided to close this issue.
