### ISSUE TITLE
User Defined Settings and expressions and string interpolations

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1161]
User defined settings is a new feature to allow the user to add custom settings to a test step. This is not very useful by itself, but if we add a general expressions and interpolation property this could bring a new level of flexibility and convenience to opentap.

For example, if it is wanted to sweep a set of frequencies and measure power. This could be done by adding a custom Frequency setting and a custom Power setting to the Scpi Step. The scpi steps query setting could then be configured to take the frequency as an input- and place the measurement in an output. (In reality, probably two separate steps are needed here). The Power output could  be assigned based on the measurement and some expression.

Features:
- Scpi Step and Process Step to save the output into a property that can be used by expressions.
- Expressions should support matching regular expressions.
- EnabledIf should be modified to support an expression in addition to the current property.
- ValidationAttribute and VerdictAttribute are two attributes that can be added to add more convience.
- Allow basic string interpolation-like expression for settings with string type. e.g "The frequency is: {Frequency} hz"
 More to come...
 

Related to: #1120

**Comment by rmadsen-ks** [comment]
Support for this feature has been implemented.

Mixins themselves are implemented in https://github.com/opentap/basic-mixins and https://github.com/opentap/expressions.

**Comment by sebastian-pop** [comment]
Will be tested with KS8400
