### ISSUE TITLE
Repeat Conditions for TestStep class

### ISSUE THREAD

**Issue by btyilmaz** [opentap/opentap#1171]
Users may need to repeat a test step based on its verdict. We can add a feature so that user can enable repeat conditions from the test step settings panel similar to break conditions.  

When this repeat conditions property is enabled, test step will be repeated until the condition is met. There may be additional settings such as the limit of maximum repeat count etc.

**Comment by rmadsen-ks** [comment]
This will be solved by the "Mixins" feature. #1175

**Comment by btyilmaz** [comment]
Hi @rmadsen-ks , thanks for the update. I think we can wait until releasing the mixin feature to develop a plugin for this feature.

**Comment by rmadsen-ks** [comment]
This can now be implemented as a custom plugin or used by installing the Basic Mixins plugin.
