### ISSUE TITLE
Multiple edit: Run Program: Environment Variables does not work

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1182]
**Describe the bug**

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.21.1

**To Reproduce**

1. Add two Run Program steps
2. Select both
3. Edit the `Environment variables` setting 

**Actual behavior**

Cannot add new rows

**Expected behavior**

If it's intended for this setting to be edited on multiple steps it should work

Otherwise it should be hidden on multiple selection

**Additional context**

Add any other context about the problem here. Please also attach a log file from <InstallDir>\SessionLogs\ that shows the issue when possible/relevant.

**Comment by rmadsen-ks** [comment]
This has been slightly improved by #1202, but still some modifications are needed to make it work perfectly.

**Comment by rmadsen-ks** [comment]
Actually this seems to work in the TUI now, so I will move this issue to the ks8400 issue tracker.
