### ISSUE TITLE
OpenTap.Templates.9.21.0.nupkg - Editor Reference

### ISSUE THREAD

**Issue by witoldpiet** [opentap/opentap#1204]
A new project was created using OpenTap.Templates.9.21.0.nupkg. The reference to `Editor` is defined this way:
```xml
<ItemGroup Condition="'$(DebugWith)' == 'Editor'">
  <OpenTapPackageReference Include="Editor" version="9.19.1"/>
</ItemGroup>
```

Wouldn't it be better do define it this way:
```xml
<ItemGroup Condition="'$(DebugWith)' == 'Editor'">
  <AdditionalOpenTapPackage Include="Editor" version="9"/>
</ItemGroup>
```

Using `AdditionalOpenTapPackage` and setting version to "9" instead of "9.19.1".

**Comment by witoldpiet** [comment]
Two more suggestions:
 - The template should include a shorter name than this: `Name = "OpenTap.Plugins.PluginDevelopmentDUT"`. Use instead the class name, i.e. `MyDUT`.
 - The template now includes this `[Display("MyTestStep")]`.  Use this instead `[Display("MyTestStep", Group: "OpenTap.Plugins.PluginDevelopment", Description: "Insert a description here")]`, so that we guide developers towards best practices.

**Comment by Operdies** [comment]
@witoldpiet where do you see `OpenTap.Plugins.PluginDevelopmentDUT`? The nupkg template you referenced always uses the name `MyDUT` as far as I can tell. But I agree with your other points.
