### ISSUE TITLE
Incomplete message in log when opening resources

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#121]
Originally filed November 23 2021 by Wooi Po Chang on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/811)

The log message `Waiting for resources to open:` seems to be incomplete
![image](https://gitlab.com/OpenTAP/opentap/uploads/b144f00af1037baa8d7f72c308109bf4/image.png)

May consider improving `PrintWaitingMessage` function in [TestPlanExecution.cs](https://gitlab.com/OpenTAP/opentap/-/blob/master/Engine/TestPlanExecution.cs)

**Comment by rmadsen-ks** [comment]
This is due to a race condition occuring inside PrintWaitingMessage. The solution is to fetch the unopened resource before printing the first message, so we ensure that something coherent is written.
