### ISSUE TITLE
Reinstalling/updating OpenTAP plugin resolves oldest version (instead of newest)

### ISSUE THREAD

**Issue by PelleRavn** [opentap/opentap#1211]
**Describe the bug**

When (re-)installing the OpenTAP plugin for it to be updated to the newest version, it resolves the oldest version, instead of the newest version available. Also, it seems that it completely ignores that I specified the OS and Architecture parameters, and installing another one, even though there is a package available for the OS and Architecture specified.

**Environment:**

 - OS: MacOS 13.5 (arm64)
 - OpenTAP Version 9.22.0-beta.X

**To Reproduce**

1. Create or checkout a plugin that resolves the (almost newest) OpenTAP Nuget Package (in this case: `version 9.22.0-beta.17+cc77ae1c` for the `arm64` architecture).
2. Build the project and navigate to the `bin/Debug` folder of the tap CLI.
3. Check installed packages (`./tap package list -I`), should only show OpenTAP.
4. Install OpenTAP to get it to the newest beta `./tap package install OpenTAP --version beta --architecture arm64 -os MacOS`.

**Actual behavior**

Running the steps above, it resolves OpenTAP to version `9.22.0-beta.1+902e1c86` for the `x64` architecture:

```
➜  cd bin/Debug
➜  ./tap package list -i
OpenTAP - 9.22.0-beta.17+cc77ae1c - installed
➜  ./tap package install OpenTAP --version beta --architecture arm64 --os MacOS
Package 'OpenTAP' has missing files and is broken.
Repository '/Users/pellravn/Projects/Plugin/bin/Debug' is ambiguous. It will be interpreted as a directory. Please specify a URI scheme if this is not correct.
OS or Architecture were specified without --force. Only compatible packages will be selected.
Selected package OpenTAP architecture x64 instead of arm64
Downloaded 'OpenTAP' to '/Users/pellravn/.local/share/OpenTap/PackageCache/OpenTAP.9.22.0-beta.1+902e1c86.x64.Linux,MacOS.TapPackage'. [1.53 ms]
Installing to /Users/pellravn/Projects/HawkeyePlugin/bin/Debug
Uninstalled OpenTAP version 9.22.0-beta.17+cc77ae1c. [9.82 ms]
Installing /Users/pellravn/.local/share/OpenTap/PackageCache/OpenTAP.9.22.0-beta.1+902e1c86.x64.Linux,MacOS.TapPackage
Starting install step 'chmod +x tap'
Succesfully ran install step  'chmod +x tap'.  [39.6 ms]
Installed OpenTAP version 9.22.0-beta.1+902e1c86 [116 ms]
```

**Expected behavior**

Installing/updating OpenTAP with the command above should resolve the newest version (at the time of writing it is `9.22.0-beta.19+a447c28d` for the `arm64` architecture).

**Additional context**

Attached the SessionLog for the install action:
[SessionLog 2023-08-16 10-45-35.txt](https://github.com/opentap/opentap/files/12358311/SessionLog.2023-08-16.10-45-35.txt)

**Comment by alnlarsen** [comment]
I am not able to reproduce this on Linux. I will test this on a mac when I can get my hands on one.

**Comment by alnlarsen** [comment]
I have acquired a mac. I can confirm there is definitely some funky behavior
