### ISSUE TITLE
Installing/uninstalling system-wide packages fails without error

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1243]
**Describe the bug**

**Environment (please complete the following information):**

 - OS:Windows 10
 - OpenTAP 9.21.1

**To Reproduce**

1. `tap package install "Keysight Fixed License Manager"

2. Click Continue on the elevated prompt

**Actual behavior**

No error displayed in the CLI

Keysight Fixed License Manager is not installed

**Expected behavior**

In case the installation fails, an error should be displayed

Keysight Fixed License Manager should be installed

**Additional context**

There are also issues when uninstalling

**Comment by sebastian-pop** [comment]
Verified on OpenTAP 9.22.0-beta.43

Install works

Uninstall does not work. Reopening
![image](https://github.com/opentap/opentap/assets/97734470/6025b609-453c-4cb9-a89b-4d4a14376ebf)

**Comment by alnlarsen** [comment]
@sebastian-pop does uninstall work if you are already running elevated? I don't think we ever implemented elevation for uninstall

**Comment by alnlarsen** [comment]
Elevating for uninstall actions was never implemented in the first place. The issue you are describing is not relevant to this issue. Uninstalling from a manually elevated shell works correctly. Closing this.

**Comment by sebastian-pop** [comment]
Uninstall issue here https://github.com/opentap/opentap/issues/627

Install works now on 9.22.0-rc.1
