### ISSUE TITLE
'Tap package verify' command fails for OpenTAP if it was installed from the CLI

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1252]
**Describe the bug**

Looking at these fixed scenarios https://github.com/opentap/opentap/pull/1238, it works for OpenTAP installed using the installer but not when OpenTAP is installed using the CLI

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.22.0-beta.43

**To Reproduce**

1. Install OpenTAP using the installer
2. Run `tap package verify` - > OpenTAP is verified
3. Run `tap package install OpenTAP --version beta` - > This will reinstall the same version of OpenTAP in this case
4.  Run `tap package verify` - > OpenTAP is not verified

**Actual behavior**

![image](https://github.com/opentap/opentap/assets/97734470/0f444d80-390b-4b93-a629-4756ee47da4e)

**Expected behavior**

OpenTAP should be verified in this scenario too

**Additional context**

Log: [Latest.txt](https://github.com/opentap/opentap/files/12725429/Latest.txt)

**Comment by rmadsen-ks** [comment]
The hash of tap.exe should not be checked when updating.

**Comment by sebastian-pop** [comment]
Fix confirmed on 9.23.2-beta.16

**Comment by bogdan-achim** [comment]
Verified as fixed
