### ISSUE TITLE
Warning shown when listing packages in the default folder

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1259]
**Describe the bug**

Warning displayed due to folder path

**Environment (please complete the following information):**

 - OS: Ubuntu 22.04
 - OpenTAP 9.22.0-rc.1

**To Reproduce**

1. Install OpenTAP in the default folder using the installer `/opt/opentap`
2. Run `tap package list` 

**Actual behavior**

Warning shown

![image](https://github.com/opentap/opentap/assets/97734470/0ecadd05-1ad8-44ea-8b5f-d14eee50347a)

**Expected behavior**

The user should not receive warnings when installing in the default folder

**Comment by rmadsen-ks** [comment]
Closed by #1261
