### ISSUE TITLE
Add the version to the linux installer file. Currently it's `OpenTAP`

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1262]
**Environment (please complete the following information):**

 - OS: Ubuntu
 - OpenTAP Version 9.22.0-rc.1

**To Reproduce**

1. Download the linux installer from an action workflow
Windows https://github.com/opentap/opentap/suites/16574533943/artifacts/946850569
Linux https://github.com/opentap/opentap/suites/16574533943/artifacts/946850569

**Actual behavior**

Windows file name: `OpenTAP.9.22.0-rc.1`
Linux file name: 'OpenTAP'

**Expected behavior**

Linux file name should also be `OpenTAP.9.22.0-rc.1`

**Comment by alnlarsen** [comment]
@sebastian-pop this is intentional. It only affects the artifacts. (There is an issue with opentap.io because it is using an incorrect query argument for downloading the Linux installer)
