### ISSUE TITLE
Parameterized mixin remains after removing the mixin itself

### ISSUE THREAD

**Issue by Razvan-Muresan** [opentap/opentap#1291]
**Environment (please complete the following information):**

 - OS: Windows 10, 64-bit

 - Test Automation 9.22.0-rc.3

**To Reproduce**

1. Add a mixin
2.  Parameterize on Test Plan
3. Remove mixin

**Actual behavior**

Mixin was removed but it's still a parameter

**Expected behavior**

Parameterized mixin should be removed

![parammix](https://github.com/opentap/opentap/assets/132340651/ff66de42-a1e9-4dba-a962-56176d0ce7a4)

**Comment by rmadsen-ks** [comment]
This was fixed by #1295
