### ISSUE TITLE
Error when loading a test plan with a mixin as a test plan parameter

### ISSUE THREAD

**Issue by Razvan-Muresan** [opentap/opentap#1292]
**Environment (please complete the following information):**

 - OS: Windows 10
 - Test Automation 9.22.0-rc.3

**To Reproduce**

1. Add any step
2. Open test plan parameters
3. Add a mixin
4. Save the test plan
5. Reload the test plan

**Actual behavior**

Error in log [Latest (1).txt](https://github.com/opentap/opentap/files/12867854/Latest.1.txt)

![image](https://github.com/opentap/opentap/assets/132340651/38db5d99-6d87-42db-854f-b6ff227c3188)

**Comment by rmadsen-ks** [comment]
This was closed by #1295.
