### ISSUE TITLE
Test Plan Reference: Expression on loaded test plan parameter not displayed

### ISSUE THREAD

**Issue by Razvan-Muresan** [opentap/opentap#1296]
**Environment (please complete the following information):**

 - OS: Windows 10
 - Test Automation 9.22.0-rc.3

**To Reproduce**

1. Add a Delay step
2. Parameterize Time Delay
3. Add an expression on the parameterized Time Delay
4. Load this test plan into a Test Plan Reference

**Actual behavior**
The expression on the Time Delay parameter is not loaded

**Comment by rmadsen-ks** [comment]
Actually, I don't see this as a big problem - Test Plan Reference does not support expressions yet. I think that is ok. I cannot see a huge use for that.

**Comment by rmadsen-ks** [comment]
In the newest version this is displayed, but the expression can be modified which needs to be fixed in ks8400.
