### ISSUE TITLE
Align tap sdk new and dotnet new opentap

### ISSUE THREAD

**Issue by PelleRavn** [opentap/opentap#1319]
If I create a new project using `tap sdk new project <name>`, it will correctly create a new project.
But the template for the included TestStep will be named the same as the project. So if I call the project "SomePlugin", the TestStep inside will look like this:

```
namespace SomePlugin
{
    [Display("SomePlugin")]
    public class SomePlugin : TestStep
    {
        // The rest of the template ignored
    }
}
```

If I, on the other hand, create the template with `dotnet new opentap`, it will create a TestStep that looks like this:

```
namespace SomePlugin
{
    [Display("MyTestStep", Description: "Insert a description here", Group: "SomePlugin")]
    public class MyTestStep : TestStep
    {
        // The rest of the template ignored
    }
}
```

I think the one created with `dotnet new` is more correct, as it is a little misleading for new users of OpenTAP, that the class created in `SomePlugin.cs` is not related to the overall plugin, but actually a TestStep that is just named incorrectly. 

In general, I think that the templates generated should be the identical, and not generate two different results. Another example of this is the `DisplayAttribute` added, it has a lot more details on the `dotnet new` template.

Was created using OpenTAP/SDK version 9.22.2+1f88c8b1.

/Pelle

**Comment by rmadsen-ks** [comment]
This should definitely be aligned. We should find a way of ensuring that the same code is being used for generating the templates?

**Comment by alnlarsen** [comment]
@rmadsen-ks I agree that it would be great if both methods aligned their output by invoking the same code. How I understood `dotnet new` templates, they use a declarative syntax, and don't really allow hooking into custom code, so maybe the `tap sdk` actions should just call `dotnet new` under the hood?

**Comment by bogdan-achim** [comment]
Verified in OpenTAP v9.24.0-rc.1

![image](https://github.com/opentap/opentap/assets/118886454/a56c432c-2868-460c-9948-47e448617037)
