### ISSUE TITLE
Child TestSteps are sometimes serialized as GUIDs

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1331]
I have seen this multiple times, but it is hard to reproduce.

Sometimes child test steps can be serialized as their guids instead of their values. This is a big problem because it causes a dataloss when the application is closed.

This was seen while working with expressions or mixins.

**Comment by rmadsen-ks** [comment]
Since this was reported commit c7a164ee seems to have introduced some extra safety. We will close this for now as fixed, but keep an eye on if it reappears.

**Comment by bogdan-achim** [comment]
QA can't verify
