### ISSUE TITLE
OpenTAP fails to build locally

### ISSUE THREAD

**Issue by brocci** [opentap/opentap#1346]
I just made a fresh clone of the main branch and attempted to build it using VS2019:

![OpenTAP_Build_Fails](https://github.com/opentap/opentap/assets/2153249/6c827ef8-8e97-43bd-83e8-b49840b4ed48)

Looks like _evt_ being declared in the if statement it is not longer available when used in _SetElementValues_.

Possible fix:

```csharp
            if (obj is Event)
            {
                Event evt = (Event)obj;
                node.SetElementValue(nameof(evt.Timestamp), evt.Timestamp);
                node.SetElementValue(nameof(evt.Message), evt.Message);
                node.SetElementValue(nameof(evt.Source), evt.Source);
                node.SetElementValue(nameof(evt.EventType), evt.EventType);
                return true;
            }
            else
            {
                return false;
            }

Same issue if I take the source code from the zip file for the 9.22.3 release.

**Comment by rmadsen-ks** [comment]
Hi @brocci, can you try installing the latest .net developer pack from https://dotnet.microsoft.com/en-us/download/visual-studio-sdks?

**Comment by brocci** [comment]
Hi @rmadsen-ks. Will try, but I think my VS2019 is already using 4.8. Is there any requirement to use VS2022 or above, or .Net6.0 or above?

**Comment by rmadsen-ks** [comment]
It is not something we have explicitly selected, so I don't know. You can try to install it and see if it works.

**Comment by brocci** [comment]
I have VS2022 installed on a virtual machine. Will try that first.

**Comment by brocci** [comment]
OK. I did the test using VS2022 with a clone of the main branch, and the build succeeded.

So this means that the scope of an object has changed between the two versions of SDKs. My VS2019 has .Net Framework 4.8 and .Net 5.0. VS2022 comes with .Net Framework 4.8 and .Net 7.0.

As a consequence, I guess VS2022 / .Net 7.0 or above is required to build OpenTAP (If the code is not made compatible with previous versions).
And docs.opentap.io would need to be updated:

[
![OpenTAP_Requirements](https://github.com/opentap/opentap/assets/2153249/c39b0016-0d37-46b2-90a8-5232fee84a47)
](url)

**Comment by rmadsen-ks** [comment]
I am not sure I understand.  If you want to build OpenTAP from source there might be other requirements than the requirement for building OpenTAP Plugins. doc.opentap.io is for plugin developers, not for developing the OpenTAP source itself.

**Comment by brocci** [comment]
Yes. Sorry. You are right. 
It is just that in my case, I need to build OpenTAP in Debug mode to understand why my plugin is causing OpenTAP to raise an exception. So it seems I need to upgrade to VS2022...

**Comment by rmadsen-ks** [comment]
Ok, well, you are anyway not completely wrong. Our readme should contain the right info, but doesn't https://github.com/opentap/opentap#building-opentap

Are you saying that it did not help to install .net 4.8 developer pack or dotnet sdk, but you definitely needed to upgrade to VS 2022 for it to build?

**Comment by brocci** [comment]
I haven't tried to install .net 4.8 in my VS2019 because it was already there apparently:

![netsdk](https://github.com/opentap/opentap/assets/2153249/321b5359-877d-4104-a8a5-0318f1d22399)

So I tested directly with VS2022.

What I could try is to install .Net 7.0 or above to see if it builds correctly with VS2019...

**Comment by brocci** [comment]
Well, it seems that .Net SDKs 6.0 and above are only compatible with VS2022:

![sdk7](https://github.com/opentap/opentap/assets/2153249/0fa18c2f-1b28-447c-b301-b602879e9866)

So I could install it, but I would have to use the command line to build (dotnet build).

**Comment by bogdan-achim** [comment]
Verified
