### ISSUE TITLE
Properties of TestSteps added by TestPlanReference is not readonly in Annotations

### ISSUE THREAD

**Issue by Denrask** [opentap/opentap#1352]
**Describe the bug**

The Runner and TUI does not display properties of ReadOnly TestSteps as Readonly.

**To Reproduce**

1. Create a TestPlan containing a Delay step
2. Load that plan using a TestPlanReference Step
3. The "Time Delay" property is not readonly from an Annotation perspective

**Comment by bogdan-achim** [comment]
Verified with KS8400 v9.23.0-rc.5
