### ISSUE TITLE
Allow Assignment of Outputs to Members with Compatible Types

### ISSUE THREAD

**Issue by timremm** [opentap/opentap#1368]
At present, the assignment of outputs is restricted to members with identical types. It would be beneficial to extend this capability to include types that are compatible through casting. For instance:

**Scenario 1:**

Output Type: int
Input Type: double
Assignable: Yes

**Scenario 2:**

Output Type: float
Input Type: double
Assignable: Yes

**Scenario 3:**

Output Type: double
Input Type: int
Assignable: No

This enhancement would improve flexibility and usability by allowing assignments between types that can be safely casted, expanding the range of scenarios where outputs can be effectively assigned to members.

**Comment by rmadsen-ks** [comment]
I agree with this, but many we should also add.

Output Type: T
Input Type: Super-class of T
Assignable: yes

This way, input type could be IConvertible and output type could be String,double,float,...
