### ISSUE TITLE
Incorrect file reference

### ISSUE THREAD

**Issue by Marc-vd-Klooster** [opentap/opentap#1370]
There is a incorrect file reference in the example for CustomBenchSettings.
It references to ' AccessingComponentSettings.cs' at line 23, but that file is renamed to 'SettingsRetrieval.cs'.

https://github.com/opentap/opentap/blob/3338a1acd368c6fc978884f114cf3a4c2e4d7583/sdk/Examples/PluginDevelopment/GUI/CustomBenchSettings.cs#L23C29-L23C29

**Comment by rmadsen-ks** [comment]
Hi @Marc-vd-Klooster,

Thanks for highlighting this. I have added a fix for 9.24.0.
