### ISSUE TITLE
OpenTAP latest installer download is 9.21 instead of 9.22

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1371]
**Describe the bug**

The latest installer is missing from the repo

**To Reproduce**

1. Go to https://opentap.io/downloads

2. Download the Windows or Linux installer

**Actual behavior**

Version 9.21 is downloaded

**Expected behavior**

Version 9.22 should be downloaded.
The download link gets the latest installer. It means that the 9.22 installer is not on the repo

**Additional context**

This might be caused by the repo update

**Comment by rmadsen-ks** [comment]
This was found to be a bug in the repository server.

Closing it here.
