### ISSUE TITLE
Clean Up Test Plan

### ISSUE THREAD

**Issue by btyilmaz** [opentap/opentap#1376]
While we were developing test plans, we encountered an issue that we needed to reset some devices to a known state when the test plan is breaked or aborted. 

I currently solved this problem by developing a plugin (ITestPlanRunMonitor) that runs a clean up test plan created by the user. 

I think it might be a nice feature to add to the OpenTap engine. When a test plan is breaked or aborted, specified clean up test plan can be run.

**Comment by rmadsen-ks** [comment]
Hi @btyilmaz and thanks for requesting the feature.

This can be done in a few ways already today(described below). Can you use one of them?

Option 1: Use a parent step

When a test step runs with an error, that is reflected in the TestStepRun. If you place the step in a parent step, the parent step can handle the error.

Option 2: Use PostPlanRun

Override the post plan run event on some event in the test plan:

```cs
public override void PostPlanRun()
    {
        // Do something with PlanRun
        base.PostPlanRun();
    }
```

**Comment by btyilmaz** [comment]
Hi @rmadsen-ks , thanks for suggestions.

Option 2 is not something we want to do because what the clean up will do is dependent on the test and we don't want to change plugins for different tests.

About option 1, I did not realize before that we could remove the break conditions. I will work on it if there is any downside of this option, but for now I think our issue is resolved.

Thanks

**Comment by rmadsen-ks** [comment]
It sounds like this issue is resolved, so I will close it for now.
