### ISSUE TITLE
Allow setting a repository token from the CLI

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1383]
We support adding repository authentication in `AuthenticationSettings.xml`, but there is no simple way to specify a token on the CLI when using e.g. `tap package download` or `tap package install`. We should support e.g. `--token <user_token>`. This will enable users to easily install non-public packages uploaded to `packages.opentap.io`.

**Comment by bogdan-achim** [comment]
Verified on OpenTAP v9.24.0-rc.1 using a User Token with the Production API/packages link
