### ISSUE TITLE
IEEE bin block reading fails

### ISSUE THREAD

**Issue by kaushik-keysight** [opentap/opentap#1399]
Reported by customer

**Describe the bug**

The `ScpiQueryBlock<double>(Scpi.Format("FETCh?"));` fails in the `DoReadIEEEBlock` private function with `“-2147221439 The Safearray cannot be converted to the desired type."` exception.

Reading the array of doubles as `byte[]` the `ScpiQueryBlock(Scpi.Format("FETCh?"));` does not help, it returns the truncated array until the first `‘\n’ = 0x0A`.

Reading the data as `ASCII` works, however, it is incredibly slow in OpenTAP (e.g. 10 seconds for 10k samples). It seems that parsing of the data in TAP is the bottleneck, since the Interactive IO in the ConnectionExpert received the ASCII data within a fraction of a second.

Also:

1) the 34465 DMM returns indefinite length IEEE binblock (although the documentation suggests a definite length block). You can easily check this in IO monitor.

2) The TAP internal `DoReadIEEEblock` function stops reading of the indefinite length binblock when it finds terminating character (0x0A, newline) this value may also appear as a part of data somewhere within the binblock. In such case, the the remaining part of the binblock is lost.

**Environment (please complete the following information):**

 - OS: [e.g. Windows 10]
 - OpenTAP Version [e.g. 9.17.0]

Two possible solutions:

1. The 34465 would return definite length binblock (as is written in the programing guide)

2. TAP ScpiInstrument class would have function to read binblock with specified length. It is possible to get the number of samples by a different query from the 34465 DMM, so I know how many bytes should be read.

**Comment by rmadsen-ks** [comment]
Hi @kaushik-keysight, I am not sure if this is something we can fix. Do you know if this is part of the standard?

If you just want to read raw bytes, it is possible using something like ```((IScpiInstrument) instrument).IO.Read()```.
Read has the following signatur: ```ScpiIOResult Read(ArraySegment<byte> buffer, int count, ref bool eoi, ref int read);```

**Comment by kaushik-keysight** [comment]
[34465A Logs and code.zip](https://github.com/opentap/opentap/files/14100881/34465A.Logs.and.code.zip)

I am not sure if this is part of the standard. Maybe some logs would help?

**Comment by alan-copeland-keysight** [comment]
Good data gathering @kaushik-keysight !

The instrument is returning "IEEE Indefinite-length binary block" which is inconsistent with what the user manual describes _(I will submit this as a defect with the instrument firmware team. I verified with 34470A and firmware 3.0.3)_

The problem with indefinite-length binary block is the fact that you can have these terminating characters mid-datastream. This is a tough data format and usually only used for a "data streaming" type application where the instrument is just going to pump out data forever and never have a terminator in the data (oscilloscopes use this sometimes). Pretty niche.

I agree the right workaround is to use Read(...) like @rmadsen-ks  recommends. Read (3 + (8 * number of readings)) bytes, then convert the data within the user program.

#0<data>\n

The data conversion algorithm can be copied from here:
https://gitlab.com/OpenTAP/opentap/-/blob/master/Engine/ScpiInstrument.cs#L821-854 

@alnlarsen - FYI
