### ISSUE TITLE
Available Values Example: Copy-paste step will not copy parameterized settings

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1401]
**Describe the bug**

**Environment (please complete the following information):**

Windows 10, 64-bit

Test Automation 9.18.3

**To Reproduce**

1. Have Example plugins installed
2. Add a `Available Values Example` step
3. Set values for all settings
4. Parameterize all settings on test plan
5. Copy-paste step

**Actual behavior**

AvailableValues and SelectedValues settings are not parameterized on copied step. Log:
[SessionLog_2022-10-19_01-22-16.txt](https://github.com/opentap/opentap/files/14053605/SessionLog_2022-10-19_01-22-16.txt)
![copypasta](https://github.com/opentap/opentap/assets/97734470/189c3423-a082-4f2a-ba25-8d8f56d6aba1)

**Expected behavior**

**Additional context**

Add any other context about the problem here. Please also attach a log file from <InstallDir>\SessionLogs\ that shows the issue when possible/relevant.

**Comment by rmadsen-ks** [comment]
This is not a bug. For parameterisations to work the thing needs to be trivially copyable and in this case it is not. This is also expressed by the warning in the log.
