### ISSUE TITLE
Flaky unit test improvements

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1416]
- Engine test times out intermittently after 20 minutes during CI builds. We need to figure out which test causes this. Could it be related to user input
- CyclicDependenciesTest during test packages can also fail.
- Set the test timeout to 5 minutes(normally it takes around 2m30s for it to pass)

**Comment by alnlarsen** [comment]
Also failing:
```
  Failed TestGetObjectSettings [20 ms]
```
