### ISSUE TITLE
Idle results

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1425]
Add support for idle measurements.

Idle measurements are measurements that happens out of band without a test plan running.

The api can be accessed through IdleResults

```cs
IData[] IdleResults.GetIdleResults();
```

```cs
// this interface can be implemented by instruments, duts and component settings.
interface IIdleResults{
     IData[] GetIdleResults();
}
```

Alternative idea:
```cs
        public class IdleResultTestInstrument : Instrument
        {   //...
            [Result]
            [Browsable(true)]
            [Unit("Hz")]
            [Display("V", Group: "Metrics")]
            public double Voltage => /* */ 1.0;

        }
```

**Comment by rmadsen-ks** [comment]
Moving this out of the milestone to give it more time to mature.

Consider if it should be a separate package.

**Comment by rmadsen-ks** [comment]
This will be a separate package and we wont track it for 9.25.

**Comment by jfaaborg** [comment]
https://packages.opentap.io/#name=%2FPackages%2FMetrics&version=0.1.0%2Bc80cbf68&os=Windows%2CLinux%2CMacOS&architecture=AnyCPU
