### ISSUE TITLE
Fix GitHub warnings

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1440]
We get a lot of warnings at the bottom of all of our pipelines. Let's clean this up. See screenshot:

![image](https://github.com/opentap/opentap/assets/95965749/afddecd2-859d-4fd3-a067-09b8b607b410)

**Comment by rmadsen-ks** [comment]
Before the fix 55 warnings: https://github.com/opentap/opentap/actions/runs/8169238142
After the fix 49 warnings: https://github.com/opentap/opentap/actions/runs/8189305872


Still not quite there, but it helps.

**Comment by bogdan-achim** [comment]
> Before the fix 55 warnings: https://github.com/opentap/opentap/actions/runs/8169238142 After the fix 49 warnings: https://github.com/opentap/opentap/actions/runs/8189305872
> 
> Still not quite there, but it helps.

Verified based on the links provided
