### ISSUE TITLE
Text Log Result Listener: Filtering out one or more options will throw an error in the Log Panel

### ISSUE THREAD

**Issue by Razvan-Muresan** [opentap/opentap#1446]
**Describe the bug**
Changing the Filter option for a Text Log Results Listener will throw an error in the Editor Log Panel
![image](https://github.com/opentap/opentap/assets/132340651/51a6373e-11de-45da-98fc-1b2759089e08)

**Environment (please complete the following information):**
 - OS: Windows 10
 - OpenTAP Version 9.23

**To Reproduce**
1. Add a Log Text Result Listener
2. From Filter Options of the Text Log Result Listener uncheck Error
3. Run a test plan

**Actual behavior**
An error is displayed in the log panel, however the log result txt file contains only filtered type of messages

**Expected behavior**
The Test Plan should be completed without errors and the generated log.txt file should contain only checked options, in this case Debug / Information and Warning messages.

**Comment by rmadsen-ks** [comment]
Closed by #1449

**Comment by Razvan-Muresan** [comment]
Verified using OpenTAP version 9.23.2 and KS8400 version 9.23.0-beta.27
