### ISSUE TITLE
Copyright: Update copyright to year 2024 in the License.txt file

### ISSUE THREAD

**Issue by Razvan-Muresan** [opentap/opentap#1450]
**Describe the bug**
In the installation folder, the License.txt file displays `© Keysight Technologies 2012-2023`

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.23.2-rc.4

**To Reproduce**
1. Open LICENSE.txt file from the installation folder

**Actual behavior**
![image](https://github.com/opentap/opentap/assets/132340651/9cb04697-1277-4e8d-9706-949ef1c2aff8)

**Expected behavior**
The year displayed should be 2024

**Comment by alnlarsen** [comment]
This has been fixed

**Comment by bogdan-achim** [comment]
Verified in OpenTAP v9.24.0-beta.33

![image](https://github.com/opentap/opentap/assets/118886454/ca8b5438-7a19-4287-9857-63607b8fb8a8)
