### ISSUE TITLE
Update `Break Conditions` documentation

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1452]
https://doc.opentap.io/User%20Guide/Introduction/#verdicts

```
When a break condition is encountered, execution of all child steps is stopped, and the test plan resumes from the point where the break was encountered.
```

It should be clear that break conditions affect the parent step.

**Comment by heintz427** [comment]
07 Mar 2024: Updated \opentap\doc\User Guide\Introduction\Readme.md to add note about parent steps.
PR: https://github.com/opentap/opentap/pull/1463
