### ISSUE TITLE
Visual Studio Template Support

### ISSUE THREAD

**Issue by heintz427** [opentap/opentap#1462]
Since the documents noted below are specific to OpenTAP (vs. KS8400), the issue was replicated from /opentap/KS8400 (https://github.com/opentap/KS8400/issues/887 -- now closed) to here in the /opentap project... 

Moving forward from 9.23, we will only support OpenTAP project templates in VS 2022 (or higher). This means dropping support for VS2019. We should update:

- [x]  https://www.keysight.com/zz/en/assets/7018-05962/technical-overviews/5992-2658.pdf
- [x]  https://www.keysight.com/zz/en/assets/3122-2146/data-sheets/PathWave-Test-Automation-Community-License-Built-on-OpenTAP.pdf
- [ ]  https://doc.opentap.io/Developer%20Guide/Introduction/#keysight-test-automation

NOTE: Both these PDF's should be updated to Ubuntu 20.04 LTS or higher (instead of 18.04)

**Comment by heintz427** [comment]
07 Mar 2024: Updated \opentap\doc\Developer Guide\Introduction\Readme.md to update to VS 2022.
PR: https://github.com/opentap/opentap/pull/1463

**Comment by bogdan-achim** [comment]
Verified in v9.24.0-rc.1
