### ISSUE TITLE
Empty logs while logs rollover

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1464]
**Describe the bug**

An extra empty log is created

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.23.2

**To Reproduce**

1. Delete all logs in the SessionLogs folder
1. Run the attached test plan: [OneMaxLog.TapPlan.txt](https://github.com/opentap/opentap/files/14538061/OneMaxLog.TapPlan.txt)
2. Verify the SessionLogs folder

**Actual behavior**

First log, max size 994 MB
Second log _1 365MB
Third log _2 and Latest both same content at 1KB

![image](https://github.com/opentap/opentap/assets/97734470/5373dea9-5aa8-4d97-945f-ae8654e895bd)

**Expected behavior**

Thrid log _2 should not be created and Latest should be the same as the Second log _1

**Comment by bogdan-achim** [comment]
Verified in v9.24.0-rc.1

Opened [new ticket](https://github.com/opentap/opentap/issues/1518)
