### ISSUE TITLE
Log rollover does not work when producing data too fast

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1471]
Since the `FileTraceListener` implementation uses an auto flushing `StreamWriter` with an underlying `FileStream`, session logs cannot roll if session log data is being produced faster than we can write to the underlying block device. See the test plan included in #1464 for an example of how to reproduce it.

This happens because `FileTraceListener` attempts to flush pending messages before detaching itself from the set of LogListeners, and then re-attaching a new log listener. I propose doing the renaming within `FileTraceListener` itself.

**Comment by sebastian-pop** [comment]
Log rollover correctly works now 9.24.0-rc.1
