### ISSUE TITLE
MixinBuilder ToDynamicMember is called multiple times

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1483]

**Comment by rmadsen-ks** [comment]
**Testing:** This cannot be QA tested directly, but it affects expressions, mixins and test plan reference. Maybe try loading making something like multiple levels of test plan reference which uses mixins, parameterizes mixins and uses expressions.

**Comment by bogdan-achim** [comment]
Verified in 9.24. This issue cannot be reproduced using mixins, parameterizing mixing and using expressions in different levels of test plan referencing.
