### ISSUE TITLE
Duplicate Type names should produce a warning during startup

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1503]
Example:
- OpenTap.Plugins.A from assembly PluginAssembly1.dll
- OpenTap.Plugins.A from assembly PluginAssembly2.dll

**Comment by sebastian-pop** [comment]
Tested with two plugins using the same namespace. The second plugin is not loaded. warnings not displayed

OpenTAP 9.25.0-beta.47

**Comment by sebastian-pop** [comment]
Fixed in OpenTAP 9.25.0-rc.1

@Oeh1995 can you add a closing `'` at the end of the second plugin name



![Image](https://github.com/opentap/opentap/assets/97734470/03466bae-5ddd-4936-96bf-eea60b0c68ed)
