### ISSUE TITLE
docs: search function not functional

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1515]
Our docs page uses Algolia to provide searches. It seems that the Algolia indexer stopped working a while ago and is no longer indexing. This leads to confusing search results. For example, searching for 'Mixins' yields 0 hits, though we added Mixin documentation months ago.

We should get Algolia working again, or find an alternative.

**Comment by rmadsen-ks** [comment]
@StefanHolst is working on an improved client-side search experience.

**Comment by sebastian-pop** [comment]
Implemented



![Image](https://github.com/opentap/opentap/assets/97734470/2eca8191-93c4-4d0e-ad05-90cede290b35)
