### ISSUE TITLE
Repeat step has 2 Iteration outputs

### ISSUE THREAD

**Issue by bogdan-achim** [opentap/opentap#1517]
**Environment**
KS8400 v9.23.0-release
OpenTAP v9.24.0-rc.1

**Describe the bug**
Repeat step has 2 Iteration outputs

**To Reproduce**
1. Upgrade OpenTAP to 9.24.0-rc.1
2. Launch KS8400
3. Add a Repeat step
4. Add a Delay child for the Repeat step
5. Add a Log Output as a child of Repeat step
6. Select the Log Output step, right-click Log Message and click Assign Output
7. Check the Output dialog

**Actual behavior**
There are 2 Outputs with the same name (e.g. Iteration from Repeat)

**Expected behavior**
There should not be 2 different settings that have the same name

**Screenshots**
![image](https://github.com/opentap/opentap/assets/118886454/3f0a0a3c-75ab-4516-a248-2a96338797be)

**Comment by Razvan-Muresan** [comment]
Verified on OpenTAP version 9.24.0-rc.2
![image](https://github.com/opentap/opentap/assets/132340651/94377ea2-b607-4a11-a2c3-d11e370bd152)
