### ISSUE TITLE
Log rollover: Latest.txt log file content is older than the one in the last log generated

### ISSUE THREAD

**Issue by bogdan-achim** [opentap/opentap#1518]
**Environment**
KS8400 v9.23
OpenTAP v9.24.0-rc.1

**Describe the bug**
The content in `Latest.txt` is older than the context in the last log file generated

**To Reproduce**

1. Delete all log files in the SessionsLogs folder
2. Launch KS8400
3. Load the attached test plan - [OneMaxLog.TapPlan.txt](https://github.com/opentap/opentap/files/15063838/OneMaxLog.TapPlan.txt)
4. Run the test plan
5. Wait for the run to finish
6. Open the SessionLogs folder
7. Compare `Latest.txt` content with the content in the last log file generated (e.g. `SessionLog 2024-04-22 16-35-05__27`)

**Actual behavior**
The content in `Latest.txt` is older than the content in the last log file

**Screenshots**
`Latest.txt` - starts at 2024-04-22 16:35:04.538635
![image](https://github.com/opentap/opentap/assets/118886454/be2ada2e-81a4-4bbf-b5f1-a4a65d3f213a)

`SessionLog 2024-04-22 16-35-05__27` - starts at 2024-04-22 16:41:36.018229
![image](https://github.com/opentap/opentap/assets/118886454/92d8a8ca-0f50-4f58-ba8d-af3884bc58c1)

**Comment by sebastian-pop** [comment]
Verified with KS8400 9.25.0-beta.1 and OpenTAP 9.25.0-beta.45 and the issue is fixed. 

The most recent log matches Latest.txt
