### ISSUE TITLE
SDK: RC version is considered Release version after OpenTAP is updated to latest RC

### ISSUE THREAD

**Issue by bogdan-achim** [opentap/opentap#1520]
**Environment**
KS8400 v9.23.2
OpenTAP v9.24.0-rc.1

**Describe the bug**
SDK Release Candidate version (v9.24) is considered Release version

**To Reproduce**
1. Install KS8400 v9.23.2 (latest release)
2. Open CMD in KS8400 installation folder
3. Run `tap package list -i`
4. Check OpenTAP version and make sure it is `9.23.2+5a906a86`
5. Check SDK version and make sure it is `9.23.2+5a906a86`
6. Launch KS8400
7. Make sure the message in the log displays the current OpenTAP version (e.g. `9.23.2+5a906a86`)
8. Close KS8400
9. Update OpenTAP in CMD using `tap package install OpenTAP --version 9.24.0-rc.1`
10. Run `tap package list -i` and check the OpenTAP version (`9.24.0-rc.1`)
11. Launch KS8400
12. Check log

**Actual behavior**
The following message is displayed in the log:
`Latest version of 'SDK' is 9.24, your version is 9.23. Please consider updating.`

**Expected behavior**
No message related to SDK should be displayed in the log as long as a new Release version does not exist

**Additional notes**
KS8400 log file - [SessionLog 2024-04-23 16-15-46.txt](https://github.com/opentap/opentap/files/15077423/SessionLog.2024-04-23.16-15-46.txt)

**Screenshots**
![image](https://github.com/opentap/opentap/assets/118886454/40bf3c33-25b6-4c5f-ad3e-d19e1f9598dc)

**Comment by alnlarsen** [comment]
This seems to have been fixed in the repository

**Comment by sebastian-pop** [comment]
This can still be reproduced but a different scenario.

1. Install KS8400 9.24.0 (with OpenTAP 9.24.2)
2. Start Editor - > Message `Latest version of 'OpenTAP' is 9.25, your version is 9.24. Please consider updating`

At the moment of testing, OpenTAP` 9.25.0` is in beta only. no rc, no release

@alnlarsen what do you think?

**Comment by sebastian-pop** [comment]
I think this can only be tested when OpenTAP 9.25 is released
