### ISSUE TITLE
Image resolution from http repositories needs better error messages

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1521]
The image resolver gives the same cryptic error message if:

1. An incorrect or expired user token is used
2. The specified http repository does not exist

In the first case, we should check if the user token is invalid by calling e.g. `ListTokens`.
In the second case, we should show an error message indicating the repository is not responding

**Comment by alnlarsen** [comment]
We should use the `WWW-Authenticate` header to indicate the error related to tokens:

![image](https://github.com/opentap/opentap/assets/95965749/6c22695d-2999-4398-855a-4767d0de9715)

**Comment by Razvan-Muresan** [comment]
Verified on OpenTAP version 9.24.0-alpha.58
