### ISSUE TITLE
Embed Properties Attribute Example: Cannot modify test step settings when more than one step is selected

### ISSUE THREAD

**Issue by Razvan-Muresan** [opentap/opentap#1527]
**Describe the bug**

Trying to edit more than one `Embed Properties Attribute Example` is throwing an Error in logs

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.24.0-rc.1

**To Reproduce**
1. Have Example plugins installed
2. Add two `Embed Properties Attribute Example` steps
3. Select both steps
4. Edit the steps

**Actual behavior**
The steps cannot be modified
This error is displayed in Logs
![image](https://github.com/opentap/opentap/assets/132340651/3814ab72-e56e-475f-b938-68555ae031b3)

**Comment by sebastian-pop** [comment]
Fixed in 9.27.0-rc.2

![Image](https://github.com/user-attachments/assets/78652b4a-7cd5-4ea6-860c-038ca53c5ad3)
