### ISSUE TITLE
`tap sdk new integration vscode -o` Output supports one file, vscode integration generates two files

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1533]
**Describe the bug**
Cannot use vscode integration with output to file

**Environment (please complete the following information):**

 - OS: [e.g. Windows 10]
 - OpenTAP Version [e.g. 9.24.0-rc.1

**To Reproduce**

1. Create a project in `c:\temp`

2. Generate vscode integration files to project folder
`tap sdk new integration vscode -o "c:\temp\pathtofile.json"`

**Actual behavior**

First file is generated. Second file wants to overwrite first file

![image](https://github.com/opentap/opentap/assets/97734470/abad0895-6494-41c8-8630-814104f90324)

**Expected behavior**

Should be able to generate both files in an output location

**Additional context**

**Comment by rmadsen-ks** [comment]
-o should be repurposed to mean  the folder where the files are located. This is also the case for when generating a solution file.

**Comment by sebastian-pop** [comment]
Fixed. Verified in 9.26.0-rc.1

![image](https://github.com/user-attachments/assets/b45094d0-14f9-4ca8-86f9-3cf03f17a792)
