### ISSUE TITLE
Creating a sdk project in opentap folder no longer displays a warning

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1534]
**Environment (please complete the following information):**

 - OS: [e.g. Windows 10]
 - OpenTAP Version [e.g. 9.24.0-rc.1 (worked in 9.23.2)

**To Reproduce**

1. `tap sdk new project MyProj`

**Actual behavior**
9.24.0-rc.1
No warning displayed, project is created

![image](https://github.com/opentap/opentap/assets/97734470/5047c766-9a95-4847-bb67-e25b3e56671c)

**Expected behavior**
9.23.2
Warning displayed and prompt to create

![image](https://github.com/opentap/opentap/assets/97734470/30df7a1d-28ee-418f-beca-dfaeeab92a1f)

**Comment by Razvan-Muresan** [comment]
Verified on OpenTAP version 9.24.0-rc.2
![image](https://github.com/opentap/opentap/assets/132340651/4c40eec3-6bba-4c80-9095-817ccf306b00)
