### ISSUE TITLE
StepRun is not thread safe

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1547]
We recently fixed a race condition in OnTestStepRunStart: https://github.com/opentap/opentap/pull/1546

The fix involved cloning the StepRun object before handing it off to result listeners, which is the correct thing to do in *this* instance, but it seems there is an expectation that StepRun is thread safe.

We should consider if it *should* be thread safe, and if so, make it so.

**Comment by rmadsen-ks** [comment]
We need this to be a bit more specific about the use cases where we need it to be thread safe.
