### ISSUE TITLE
OpenTAP Image Resolve Message

### ISSUE THREAD

**Issue by witoldpiet** [opentap/opentap#1563]
The image resolver attempts to resolve these references from a .csproj file:
```
 <AdditionalOpenTapPackage Include="Developer's System" Version="9.23.0" />
 <PackageReference Include="OpenTAP" Version="9.23.0" />
```

Should the resolver be able to bail out early from this as "Developer's System" Version="9.23.0" depends on OpenTAP Version="^9.23.2"?

Could we improve the error message when this happens? It can be difficult to figure out the root cause from this message:
 
![image](https://github.com/opentap/opentap/assets/98087587/724d8d3a-9085-44b1-883c-ac7ba210d033)

**Comment by alnlarsen** [comment]
This is related to #1525

**Comment by sebastian-pop** [comment]
new resolver error in 9.25.0-beta.43



![Image](https://github.com/opentap/opentap/assets/97734470/198051a8-7fd5-4026-a491-f5de219d1733)

**Comment by alnlarsen** [comment]
@sebastian-pop this is because Developer's System 9.23.0 requires OpenTAP 9.23.2, but I see we didn't improve the error message in this scenario. I will look into it, thanks!

**Comment by alnlarsen** [comment]
Wait actually @sebastian-pop can you explain the problem here? It looks fine to me

**Comment by alnlarsen** [comment]
Never mind, I completely misunderstood. I thought you said there was a bug with the resolver :D Forget everything I said

**Comment by sebastian-pop** [comment]
My bad, I was ambiguous with my comment. The new message for the resolver error has been updated. It's good 👍
