### ISSUE TITLE
Broken Link in Visual Studio Extension

### ISSUE THREAD

**Issue by StefanHolst** [opentap/opentap#1564]
The link ot the developer guide does not work 

`For more information on OpenTAP plugin development, see the [developer guide](https://www.opentap.io/docs/OpenTAP%20Developer%20Guide.pdf).`

https://marketplace.visualstudio.com/items?itemName=OpenTAP.opentapsdkce

The link should probably point to https://doc.opentap.io/Developer%20Guide/Introduction/

**Comment by rmadsen-ks** [comment]
Related: https://github.com/opentap/opentap/issues/1565

We should just remove it from the market place.

**Comment by alnlarsen** [comment]
@AsgerIversen removed it from the marketplace.

**Comment by sebastian-pop** [comment]
Confirmed as removed



![Image](https://github.com/opentap/opentap/assets/97734470/7155c003-81d7-4ab8-b36e-a98ba128b884)
