### ISSUE TITLE
Visual Studio Extension is not supported on Visual Studio 2022

### ISSUE THREAD

**Issue by StefanHolst** [opentap/opentap#1565]
https://marketplace.visualstudio.com/items?itemName=OpenTAP.opentapsdkce

**Comment by rmadsen-ks** [comment]
This relates to the CE version of the SDK, which should be removed from the marketplace.

**Comment by alnlarsen** [comment]
@AsgerIversen removed it from the marketplace.

**Comment by sebastian-pop** [comment]
Confirmed as removed

![Image](https://github.com/opentap/opentap/assets/97734470/37e490b1-6ed2-40d5-be16-51ee2d4259c7)
