### ISSUE TITLE
Parallel step disables "suggested next step" functionality

### ISSUE THREAD

**Issue by timremm** [opentap/opentap#1568]
**Describe the bug**

When setting the StepRun.SuggestedNextStep property to the Id of the current step, the test step will be repeated. This does not work inside a parallel step.

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.24.1

**To Reproduce**

1. Create a test step that sets StepRun.SuggestedNextStep to the Id of the current test step

2. Run inside and  outside of a parallel step

Alternative: 
1. Use any step (e.g. Delay), use Repeat Mixin from Basic Mixin Package 
2. Run inside and  outside of a parallel step

**Actual behavior**

Inside of a parallel step, the step is only executed once

**Expected behavior**

Inside of a parallel step, the step is repeated exactly as outside of a parallel step

**Comment by rmadsen-ks** [comment]
This is actually the intended behavior and why it is the "Suggested" next step. Not all test steps can necessesarily support this behavior.

This however introduces an issue with Repeat mixin.

We should add support for this by just replaying the step in the same thread as the child step requesting the next suggested step. It is very important that we wait for the step to be finished before trying to run it again.

As a minimum we should support the trivial case where the step being suggested as next is the step itself. In this case it should just replay it.

**Comment by sebastian-pop** [comment]
Confirmed as fixed on 9.25.0-beta.47
