### ISSUE TITLE
OpenTAP VS template not removed when uninstalling SDK

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1569]
**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.24.1

**To Reproduce**

1. Install SDK
2. Open VS 2022 - > Create new project - > Confirm OpenTAP template is available
3. Uninstall SDK
4. Open VS 2022 - > Confirm OpenTAP template is still available

**Expected behavior**

Installing the SDK package will install the OpenTAP VS Template. Uninstalling the SDK package should remove the template

This is how it worked when the old VS templates were in the VSSDK

**Comment by alnlarsen** [comment]
I don't think we should uninstall templates since the user could have had them installed already before installing the SDK / the user could have multiple OpenTAP installations.

I guess it's a bit strange that SDK, a local package, is installing a nuget template, which is global

**Comment by rmadsen-ks** [comment]
I also dont see any reason to uninstall it.
