### ISSUE TITLE
Include OpenTAP VS items in SDK

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1570]
**9.24.1**

Currently, the OpenTAP VS Template is included in the SDK package. The OpenTAP items (steps, instruments) are part of the VSSDK package.

Can we:
1. Include everything in the SDK package.
or
2. Move the VS Template and items in VSSDK as it used to be.

**Comment by rmadsen-ks** [comment]
Those items are only supported in Visual Studio which is why they are in the VSSDK paclage. the SDK Templates are actually dotnet templates which does not require Visual Studio to work.
