### ISSUE TITLE
Refuse to create new installations inside existing installations

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1571]
This is not a new issue. We have known that this doesn't work for several years since we have a quite old check in the `sdk new project` template for this very reason.

Someone had a problem recently because they are building into a subdirectory of `$TAP_PATH`. It looks like the Serializer and the Assembly Resolver will not always agree on which instance of types it should use. This of course causes issues when we try to create an instance of a type from an assembly which is not loaded.

I tried reproducing this on 9.24, 9.23, and 9.22, but I suspect it goes back further. 

** Steps to reproduce **
1. `tap image install 'OpenTAP:9.24' -t .`
2. `tap image install 'OpenTAP:9.21' -t subdir`
3. `./tap package install 'TUI'`
4. `./tap package list -i`

**Comment by rmadsen-ks** [comment]
Throw an exception if you try to deploy an image inside a subfolder of another installation.

**Comment by alnlarsen** [comment]
There are two sides to this issue:

1. We should not allow users to create nested installations
2. If nested installations occur due to user error, our serializer should handle it better.

1 is significantly easier than 2 and covers many scenarios.

I will create a new issue for 2.

**Comment by sebastian-pop** [comment]
Exception implemented for nested installations. Verified on OpenTAP 9.25.0-beta.43



![Image](https://github.com/opentap/opentap/assets/97734470/287fc0b8-e489-4640-ae6f-f809e0012db6)
