### ISSUE TITLE
Cannot install images from network drive

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1572]
Installing packages from a network drive (on windows) does not work. I was able to reproduce the issue by trying to install a package from my wsl package cache:

`./tap image install 'Python' -r '\\wsl.localhost\Arch\home\alex\.local\share\OpenTap\PackageCache'`

**Comment by alnlarsen** [comment]
Command output:

![image](https://github.com/opentap/opentap/assets/95965749/748fe6e6-b28e-4c78-9657-9ec1af01eaaf)

**Comment by Razvan-Muresan** [comment]
Verified on OpenTAP version 9.24.2-rc.1
