### ISSUE TITLE
Document recommendations about threading

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1574]
Add example and documentation about how best to use threading with OpenTAP.

- Parallel Step
- Defer
- Using .NET Threading
   - TaskCompletionSource
   - TapThreads
   - Dont use async methods!

**Comment by sebastian-pop** [comment]
Documentation added https://doc.opentap.io/Developer%20Guide/Appendix/Readme.html#threading-and-parallel-processing
