### ISSUE TITLE
launchSettings.json in dotnet templates has CRLF on Linux.

### ISSUE THREAD

**Issue by Denrask** [opentap/opentap#1590]
I expected LF.

**Comment by alnlarsen** [comment]
Hi @Denrask 

Which launch settings are you referring to? The file checked into source is using LF (when I clone the repository on Linux). See screenshot:

![image](https://github.com/opentap/opentap/assets/95965749/b174dc95-18e3-4857-81da-ffa2b913c561)

**Comment by Denrask** [comment]
If it's LF, then I must have done something wrong.
