### ISSUE TITLE
tap package install returns 405 Not Allowed

### ISSUE THREAD

**Issue by Denrask** [opentap/opentap#1595]
**Describe the bug**

Different "tap package" commands returns:

```html
<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.24.0</center>
</body>
</html>
```

**Environment (please complete the following information):**

 - OS: Linux
 - OpenTAP Version 9.24.2

**To Reproduce**

1. On Linux install OpenTAP 9.24.2

2. Run `./tap package install "N6705 DC Power Analyzers(v6)"`

**Actual behavior**

Installing a dependency to the `N6705 DC Power Analyzers(v6)` package and then try to install the package = 405
![image](https://github.com/opentap/opentap/assets/18167872/a1de5866-aa87-457e-8b68-914c359a2297)

Downgrade OpenTAP to 9.20 and try to install the package = success!
![image](https://github.com/opentap/opentap/assets/18167872/51342a00-ecff-4366-aff2-dd2fec4d85c7)

This might also be a weird error message case:

1. tap package install package -> Could not resolve
2. install dependency of package
3. tap package install package -> success

![image](https://github.com/opentap/opentap/assets/18167872/9bbdef15-b8be-4aa1-b955-3a77e669f220)

**Comment by alnlarsen** [comment]
The resolver error happens because N6705 DC Power Analyzers(v6) depends on SciInstrumentBase which is only available on Windows.

**Comment by sebastian-pop** [comment]
still reproduced on 9.25.0-beta.43

**Comment by sebastian-pop** [comment]
Before the fix:



![Image](https://github.com/opentap/opentap/assets/97734470/e4233a71-40d9-44e1-81e8-5741ea073d8e)

After the fix:



![Image](https://github.com/opentap/opentap/assets/97734470/ca369a44-fabb-45f6-9b4b-efa6748472bc)
