### ISSUE TITLE
Update to Newtonsoft.Json 13.0.3

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1599]
Newtonsoft.json 12.x had a known security vulnearability, namely possiblity of DDOS attack due to stack exhaustion (Many recursively nested objects).

This has been fixed in 13, where it has been limited to 64 levels, but at the same time that is a breaking change for people needing more that 64 levels.

**Comment by sebastian-pop** [comment]
Update confirmed

![image](https://github.com/opentap/opentap/assets/97734470/60c65b01-0eee-4068-92f3-aac3b66d420e)
