### ISSUE TITLE
Remove Tap.Shared

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1603]
Tap.Shared gives rise to problem with typedata caching. This is because all the code is essentially copied for each project.
 Additionally, makes the assemblies unnecessarily bigger and makes it impossible to calculate code coverage accurately.

**Comment by alnlarsen** [comment]
As a start, we can just delete the `.projitems` file and manually link files in the projects that need them. This way a project won't be compiled with files it doesn't need.

This will also reveal the files that are not being used at all / only being used in one project.

I suspect we can delete all the licensing related files.

After this is completed, we can look into splitting up the ReflectionHelper class, but let's do that later.
