### ISSUE TITLE
Update System.Text.Json to latest compatible version

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1608]

**Comment by sebastian-pop** [comment]
@alnlarsen @Oeh1995 The version of system.text.json has been updated but the version text in the folder name is old. Should this be updated too?

![image](https://github.com/opentap/opentap/assets/97734470/2abbc69d-6a90-4083-9a26-92e45dc4af97)

**Comment by alnlarsen** [comment]
@sebastian-pop I just opened it in ILSpy, and it looks like the assembly name is different from the version of the nuget package:

![Image](https://github.com/opentap/opentap/assets/95965749/4621dbd2-60a1-4bed-9f37-e4c49cdb74aa)

The folder name in OpenTAP is based on the assembly version, so we would need to hard code a new name. But thanks for raising the concern, I was definitely also surprised by version and thought we shipped an old version by mistake

**Comment by sebastian-pop** [comment]
Thanks @alnlarsen
