### ISSUE TITLE
Sweep Parameters are not stored as Result

### ISSUE THREAD

**Issue by StefanHolst** [opentap/opentap#1613]
Running a testplan with the Demonstration plugin:
The testplan has a `Sweep Parameter` that sweeps the `Charge Current` and `Discharge Current` of two charge and discharge steps.

![image](https://github.com/opentap/opentap/assets/3491693/8e4f5ef0-d179-41e6-b491-663b8ff33d54)

[e9eb9770-19c1-4028-9022-46a4d43216e6.csv](https://github.com/user-attachments/files/15888143/e9eb9770-19c1-4028-9022-46a4d43216e6.csv)

**Comment by alnlarsen** [comment]
They are stored as StepRun result parameters. This is a missing feature in the CSV plugin. Not really related to OpenTAP. Other result listeners such as SQLite *does* store this, so you can consider using a different result listener.
