### ISSUE TITLE
The error received during an installation that's not resolved should be improved

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1646]
**Describe the bug**

**Environment (please complete the following information):**

 - OS:  Windows 10
 - OpenTAP Version 9.25.0-beta.50

**To Reproduce**

1. Install KS8400 9.24.0
2. Install OpenTAP 9.25.0-beta.50 
3. Try to install OpenTAP 9.23 

**Actual behavior**

The error message displayed shows the same information twice. It's difficult to understand where the problem is

![image](https://github.com/opentap/opentap/assets/97734470/910cf951-cfcf-4f65-b166-3d8f72db5929)

**Expected behavior**

Improve the message to show the problem in the image resolver correctly

**Additional context**

In a scenario, I had messages that were interrupted/overlapping

![image](https://github.com/opentap/opentap/assets/97734470/f28107a6-b229-47e7-94c6-d3036a40bbf0)

**Comment by alnlarsen** [comment]
I think the overlapping messages is a separate problem. I think it happens because our logging implementation flushes Console.Out and Console.Error at the same time. I will open a separate issue for overlapping logs.

**Comment by sebastian-pop** [comment]
It was verified on OpenTAP 9.25.0-rc.1.

The error message has been much improved



![Image](https://github.com/opentap/opentap/assets/97734470/c630acf5-a2ef-4389-b965-e9ced3352ed3)
