### ISSUE TITLE
Linux: Error during install when choosing SDK

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1652]
**Describe the bug**

**Environment (please complete the following information):**

 - OS: Linux 22.04
 - OpenTAP Version 9.25.0-rc.1

**To Reproduce**

1. Run the installer
2. Choose to install SDK 

**Actual behavior**

Error during installation. Log: [log.txt](https://github.com/user-attachments/files/16106559/log.txt)

![image](https://github.com/opentap/opentap/assets/97734470/b03471d8-a342-4262-b2c8-0c878f950f55)

**Comment by sebastian-pop** [comment]
SDK install works on beta.59

I want to test the installer to be 100%



![Image](https://github.com/opentap/opentap/assets/97734470/bb5cac13-1c71-48ba-9d9b-4ec14fc8a46a)

**Comment by alnlarsen** [comment]
@sebastian-pop be aware that `tap sdk new project` is not going to work in this scenario since it needs the dotnet sdk. If you try it you should get a prompt to install the dotnet templates, and answering yes in this case would fail with exit code 145 also.
