### ISSUE TITLE
SDK: Error is not displayed when selecting multiple Measure Peak Amplitude steps

### ISSUE THREAD

**Issue by bogdan-achim** [opentap/opentap#1663]
**Environment**
OpenTAP v9.25.0-rc.1
KS8400 v9.24.1

**Describe the bug**
The error for Invalid Input data displayed when selecting a single Measure Peak Amplitude step is not displayed when several steps of the same type are selected

**To Reproduce**
1. Have OpenTAP and SDK installed
2. Have Visual Studio installed
3. Build the `Examples.sln` solution
4. Start the build from Visual Studio
5. Add a `Measure Peak Amplitude` step
6. Select the step and change the `InputData` field to something that displays an error (e.g. `34`)
7. Copy & paste the step
8. Select the second step and make sure the error for `InputData` is displayed
9. Select both steps

**Actual behavior**
The error for `InputData` is not displayed when both steps are selected

**Expected behavior**
The error for `InputData` should be displayed when both steps are selected

**Screenshots**

![error_not_displayed_when_multiple_steps_are_selected](https://github.com/opentap/ks8500/assets/118886454/dec83850-f9e9-453d-8367-5eae9381cc0c)

**Additional notes**
This issue also occurs on older versions of OpenTAP & SDK

**Comment by rmadsen-ks** [comment]
This was fixed by https://github.com/opentap/opentap/pull/1797

**Comment by sebastian-pop** [comment]
Fix confirmed on 9.27.0-rc.2
