### ISSUE TITLE
Make ResourceManager available outside of TestPlan

### ISSUE THREAD

**Issue by bdirenzo-keysight** [opentap/opentap#1679]
In some cases Resources need to be Opened and Closed outside of test plans. In interactive DockablePanels for instance. 
In this case we need a reference count to handle Open and Close correctly. We should just expose the ResourceManager that Test Plans already use.

**Comment by rmadsen-ks** [comment]
We need to find a solution for this as part of 9.26, although it might not be implemented in this sprint.

**Comment by rmadsen-ks** [comment]
### Testing

Unit-tests verify this behavior.
