### ISSUE TITLE
SCPI Instrument should be thread safe for ScpiQuery/Command

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1698]
We support locking the SCPI resource across devices, but not inside the process itself. 

Let's make queries and commands thread safe by adding a lock.

To test this behavior, try this:

![image](https://github.com/user-attachments/assets/b6a595fb-c590-4362-b0e5-c618b64c7c68)

**Comment by sebastian-pop** [comment]
Fix verified

Before


![Image](https://github.com/user-attachments/assets/f71199a5-3a70-4e83-a4be-4a01a5b76db0)

After




![Image](https://github.com/user-attachments/assets/8e0399b5-e3e1-4179-95d0-f0de5b50e5e8)
