### ISSUE TITLE
Error when trying to download an unavailable plugin

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1729]
**Describe the bug**

**Environment (please complete the following information):**

 - OS:  Windows 10
 - OpenTAP Version  9.26.0-rc.1 (reproduced on 9.25.0)

**To Reproduce**

1. Clear package cache
2. `tap package install Dotfuscator`

![image](https://github.com/user-attachments/assets/f6123ff8-b294-412f-816e-bc0c6971c2dc)

[Latest.txt](https://github.com/user-attachments/files/16894118/Latest.txt)

**Actual behavior**

`Unable to determine repository type for package source OpenTap.Package.InstalledPackageDefSource.`

**Expected behavior**

Not sure

When installing Dotfuscator, the same message is given but as Debug. Should it be an error or debug message?

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by sebastian-pop** [comment]
Verified on 9.27.0-rc.4. No longer reproduced

![image](https://github.com/user-attachments/assets/68a22340-cda3-4f90-950c-97e26feac4e2)
