### ISSUE TITLE
Order of arguments is different Linux vs Windows

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1730]
**Describe the bug**

**Environment (please complete the following information):**

 - OS:  Windows 10, Ubuntu 22.04
 - OpenTAP Version 9.26.0-rc.1

**To Reproduce**

1. `./tap package show –-include-plugins Demonstration`

**Actual behavior**
On Windows this works
On Linux, it does not work. Needs to be `./tap package show Demonstration –-include-plugins `

**Expected behavior**

Is this a problem?

**Comment by alnlarsen** [comment]
Looks like a bug

**Comment by alnlarsen** [comment]
@sebastian-pop I cannot reproduce this

**Comment by sebastian-pop** [comment]
Me either. It works

`./tap package show –-include-plugins Demonstration` includes a weird dash that's why it's not working
