### ISSUE TITLE
Can't add Mixins to Test Plan Reference steps

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1737]
It is not possible to add Mixins to Test Plan Reference steps. This happens because we don't allow adding mixins to "locked" steps. The way we currently check if a step is "locked" is by checking `ChildTestSteps.IsReadOnly`. This value is always true for `TestPlanReference`, and any other step which needs to internally control its child steps. 

We need a different mechanism for determining if mixins can be added in order to support mixins on steps like `TestPlanReference`.

**Comment by rmadsen-ks** [comment]
This is not actually a bug, we never allowed adding mixins to test plan reference.

**Comment by sebastian-pop** [comment]
Implemented. Verified on 9.27.0-rc.2

![image](https://github.com/user-attachments/assets/de1ad913-d1b7-4006-9486-bf778ab753e8)
