### ISSUE TITLE
SDK Template not updated

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#1742]
**Describe the bug**

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version9.26.0-rc.1

**To Reproduce**

1. Install KS8400 release 9.25.1 with SDK
2. Create a new OpenTAP project using the template in VS 2022 - > Dependecies OpenTAP 9.25.0
3. Update SDK and OpenTAP to 9.26.0-rc.1
4. Create a new OpenTAP project - > Dependencies OpenTAP 9.25.0

**Expected behavior**

The project created with the template from SDK 9.26.0-rc.1 should depend on OpenTAP 9.26.0-rc.1

**Comment by rmadsen-ks** [comment]
For me it works with the newest template. Can you verify @sebastian-pop

**Comment by sebastian-pop** [comment]
I cannot reproduce this on 9.27.0-rc.5
