### ISSUE TITLE
Intermittent memory leak with Connections and Cable Losses

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1756]
To reproduce the issue, create a connection and add 1000s of cable losses.

If the settings dialog is closed it gets cleaned up, but without closing it, these can leak due to an event handler inside Connection.

**Comment by sebastian-pop** [comment]
This is still reproduced.

KS8400 9.27.0-rc.2 with OpenTAP 9.27.0-rc.2

Steps:
1. New RF Connection
2. Open Edit Cable Loss dialog
3. Add 1000 entries - > Memory usage increases up to about 500MB
4. Scroll around in this list - > Memory usage continues to increase when scrolling 
5. Close Edit Cable Loss dialog - > Memory is still alocated
6. Close the Bench Settings dialog -> Memory is still alocated

![Image](https://github.com/user-attachments/assets/af8d7f61-dc9a-4094-b9ef-d0faab21089b)

**Comment by rmadsen-ks** [comment]
I was able to reproduce this issue, but it is not in OpenTAP this time.
