### ISSUE TITLE
TestStepList API does not raise an event when an element is set.

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1768]
When items are added or removed from a TestStepList, no event gets raised. This gives trouble for UIs that want to notify the user when the test plan has changed.

**Comment by rmadsen-ks** [comment]
### Testing

Use Test Plan Reference / Convert to sequence feature.

Verify that the new sequence step is selected after a test plan reference has been converted.

**Comment by sebastian-pop** [comment]
Fix confirmed on 9.27.0-rc.2
