### ISSUE TITLE
TestStepList: Update ID Lookup on set item

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1773]
Update the ID when SetItem is called on TestStepList.

**Comment by rmadsen-ks** [comment]
### Testing

(Related #1768)

Use Test Plan Reference / Convert to sequence feature.

Verify that the new sequence step is selected after a test plan reference has been converted.

**Comment by sebastian-pop** [comment]
Fix confirmed on 9.27.0-rc.2

Sequence step is selected after converting a test plan reference step
