### ISSUE TITLE
Reloading the GUI in every change in my testplan

### ISSUE THREAD

**Issue by arash9638444** [opentap/opentap#1778]
I need to reload my GUI everytime that I make a change in my GUI, any way to avoid that?

 - OS: Windows 11
 -  - OpenTAP Version 9.24.2

**Comment by rmadsen-ks** [comment]
Hi @arash9638444 and thanks for submitting an issue!

This is not an issue we normally see. 

Can you provide some more information about how this happens?

- What GUI are you using?
- What kind of change are you trying to make to the test plan?

**Comment by rmadsen-ks** [comment]
Forum post for more context: https://forum.opentap.io/t/about-opentap-gui/2164/2

Closing this issue now as it is not actioable.
