### ISSUE TITLE
Properties changed in TestStepPreRunEvent not reflected in result parameters

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1805]
This is an issue for use cases where parameters are being updated by a mixin: Notice that parameters are already initialized before TestStepPreRunEvent is invoked:

![image](https://github.com/user-attachments/assets/b4597e02-574d-4d71-ba7c-7d57bd325f36)

I am a bit concerned about just swapping the order since mixins could expect the parameters to already be initialized. It would probably be safest to re-calculate the parameters after invoking the mixin.

**Comment by rmadsen-ks** [comment]
This is also a problem for expressions that has properties updated with delay.

**Comment by sebastian-pop** [comment]
Excellent scenario @alnlarsen . Thank you

I can reproduce the issue on 9.26

![Image](https://github.com/user-attachments/assets/d1e18ac1-4d18-414d-b371-7cfc8a8c4b2a)

I can confirm the fix on 9.27

![Image](https://github.com/user-attachments/assets/5621837b-b656-4881-95af-e64f71793919)
