### ISSUE TITLE
SDK: Building the solution in Debug / Release triggers an error in Visual Studio

### ISSUE THREAD

**Issue by bogdan-achim** [opentap/opentap#1827]
**Describe the bug**

Building the solution in Debug / Release triggers an error in Visual Studio

**Environment (please complete the following information):**

 - OS: Win 11 x64
 - OpenTAP Version 9.27.0-rc.2

**To Reproduce**

1. Install OpenTAP v9.27.0-rc.2 with SDK
2. Open File Explorer and navigate to the OpenTAP installation folder
3. Navigate to `\Packages\SDK\Examples`
4. Open `Examples.sln`
5. Click Build -> Build Solution
6. Check the log

**Actual behavior**

The solution is built with an error:

`CS0246 - The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)`

![image](https://github.com/user-attachments/assets/aee579f7-fae3-4c65-a91f-0cf9810d9767)

`
1>------ Build started: Project: PluginDevelopment, Configuration: Release Any CPU ------
1>C:\Program Files\Keysight\TestAutomation-9.27.0-rc.2\Packages\SDK\Examples\PluginDevelopment\TestSteps\Attributes\PathAttributeExample.cs(28,16,28,28): error CS0246: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "PluginDevelopment.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========
========== Build completed at 9:36 AM and took 00.455 seconds ==========
`

**Expected behavior**

The solution is built without errors

**Additional context**

This issue is a regression, as it does not occur on OpenTAP v9.26

**Comment by rmadsen-ks** [comment]
This was fixed by #1829

**Comment by sebastian-pop** [comment]
Fix confirmed in 9.27.0-rc.4
