### ISSUE TITLE
TestPlanReference "Convert to Sequence" button does not transfer mixins that use the EmbedPropertiesAttribute

### ISSUE THREAD

**Issue by brandon-tan-keysight** [opentap/opentap#1842]
**Describe the bug**

The "Convert to Sequence" button on TestPlanReference test step does not transfer mixins that have the EmbedPropertiesAttribute.

**Environment (please complete the following information):**
 - OS: Windows 10
 - OpenTAP Version: 9.27.0-rc.4
 - Basic Mixins: 0.2.0-alpha.1.1+248e8ea6.pull-14-merge

**To Reproduce**

1. Add a Test Plan Reference test step.

2. Select any tapplan to reference.

3. Add a Limit mixin.

4. Click the "Convert to Sequence" button on the Test Plan Reference.

**Actual behavior**

Before clicking "Convert to Sequence":
![image](https://github.com/user-attachments/assets/f7de5c8f-7fab-47ea-befc-5110cfd15c63)

The referenced test plan in the above image only has a Delay step, which has its Time Delay parameterized on the Test Plan.
The Test Plan Reference test step has a Number mixin, and a Limit mixin.

After clicking "Convert to Sequence":
![image](https://github.com/user-attachments/assets/25862c81-f665-4683-bf27-595a1b261a3b)

Only the Number mixin is transferred.

When testing with only the Limit mixin, no mixins are transferred.

**Expected behavior**

Both the Number mixin and the Limit mixin should be transferred.

**Comment by sebastian-pop** [comment]
Fix confirmed

**Comment by sebastian-pop** [comment]
Fixed in 9.27.0-rc.5
