### ISSUE TITLE
RunProgram step not aborting after timeout occured

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#1855]
- Create a run program step
- Assign "C:\Windows\System32\notepad.exe"
- Set a timeout (e.g 5s)
- Run the test plan
- Expected behavior: notepad closes after 5s.
- Actual behavior: It keeps going 

Related behavior: 
If the test plan is aborted, notepad closes correctly.

See for context:

![Editor_UEAhZWTTCt](https://github.com/user-attachments/assets/a9091730-be3d-4e95-af71-3c892a5ef7f7)

**Comment by tudor9507** [comment]
tested on 9.27.1 RC 1 the issue no longer reproduces
related ticket opened #1874 due to inconsistent behavior when opening different application with a run program step
