### ISSUE TITLE
Image resolver fails to populate prerelease caches

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#1863]
This bug occurs when the following conditions are met:

1. Package A depends on package B in a prerelease version
2. The input image specifies a release version of package B
3. A compatible version of B is not present in local caches

Under such circumstances, the resolver will deem the resolution a failure before the prerelease versions of B are fetched. We must make the dependency fetching slightly more eager.

**Comment by tudor9507** [comment]
@alnlarsen  we tried this scenario: 
![image](https://github.com/user-attachments/assets/b17a7f44-ffe6-4a8d-84ce-6efa5fd60bfa)
 1. 
Package A = Test Plugin 2
Package B = OpenTAP 9.19.0-beta.53
 
2. tap image install "Test Plugin 2:1.0.3", "OpenTAP:9.19.0" -r https://packages.opentap.keysight.com/
 
3. delete OpenTAP from package cache

is it a valid scenario?

**Comment by tudor9507** [comment]
> @tudor9507 not exactly. There are a few issues here:
> 
> 1. The syntax in your screenshot is not correct. The OpenTAP version you are requesting is being ignored because of the quotes. Change `"Test Plugin 2:1.0.3", "OpenTAP:9.19.0"` to `"Test Plugin 2:1.0.3,OpenTAP:9.19.0"`
> 2. The version of OpenTAP you are requesting is _exact_ instead of _compatible_. Change `9.19.0` to `^9.19.0`.
> 3. Version `^9.19.0` is not compatible with `9.19.0-beta.53`. You should request something like `^9.18.0` instead.
> 
> So something like `"Test Plugin 2:1.0.3,OpenTAP:^9.18.0"` should reproduce this scenario

i ran the following command 
![image](https://github.com/user-attachments/assets/2cb75c65-5ee6-4100-9452-e0a5982de4f0)

the out put is 
![image](https://github.com/user-attachments/assets/51eb3bef-814f-4b9e-ba85-c1f1dcf9633f)

eventually the only packages installed are these, default packages are removed
![image](https://github.com/user-attachments/assets/a31fd51a-6cca-4d0e-bc5a-73bc234e36a2)

**Comment by sebastian-pop** [comment]
@alnlarsen we're still not sure we are testing this correctly.

Created these packages: [Original packages.zip](https://github.com/user-attachments/files/20792026/Original.packages.zip)

- PackageA version 1.0.0 depends on PackageB version ^1.1.0-beta.1
- PackageB version 1.0.0

With OpenTAP 9.26.0 and these packages in a local folder. Package cache empty. Running `tap image install "PackageA:1.0.0,PackageB:^1.0.0" -r "C:\Installed\PackageRepository"` and getting an error

```
Unable to resolve image 'PackageA:1.0.0, PackageB:1.1.0-beta.1, OpenTAP:^9.28.3-rc.1+24df3414':
No packages exist satisfying: OpenTAP: ^9.28.3-rc.1+24df3414
```

---

Scenario 2. Recreated the same packages with a dependency on OpenTAP 9.26.0 [PackageRepository.zip](https://github.com/user-attachments/files/20792081/PackageRepository.zip)

Running `tap image install "PackageA:1.0.0,PackageB:^1.0.0" -r "C:\Installed\PackageRepository` works. I was expecting it to failed based on the initial issue
