### ISSUE TITLE
Confusing statement during first time installation "Plugin already installed"

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#2]
Originally filed December 06 2021 by Janus Faaborg on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/821)

![image](/uploads/e8b2034cf79374bc6ae74108211aa382/image.png)

**Comment by StefanHolst** [comment]
Hmm. We could make some hardcoded exception for this message in the installer. @razvancoste Could you create an issue in the smartinstaller project?
