### ISSUE TITLE
tap package download multiple times

### ISSUE THREAD

**Issue by razvancoste** [opentap/opentap#200]
**Environment:**

Windows 10, 64-bit

OpenTAP 9.17.0.beta11

**Steps to reproduce:**

1. tap package download Demonstration
2. tap package download Demonstration

**Actual result:**

Demonstration is not downloaded but the message it's confusing, it was clearer before.

![image](https://user-images.githubusercontent.com/98153555/150531071-55cd1bea-3337-4654-93e3-d3832735daaa.png)
![image](https://user-images.githubusercontent.com/98153555/150533041-3f6ed2f5-6ff7-4998-be9b-320b2eed9f4c.png)

(Please also attach a log file from %TAP_PATH%\SessionLogs\ that shows the issue when possible/relevant)

**Expected result:**

OpenTAP 9.16.4

![image](https://user-images.githubusercontent.com/98153555/150530801-36b05665-8a97-438f-b90a-13cc09f58550.png)

**Other remarks:**

**Comment by rmadsen-ks** [comment]
This is actually the behavor I'd expect.
