### ISSUE TITLE
If verdict step should not be allowed to bind to it's parent

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#209]
Originally filed January 12 2022 by Mikko Ala-Kojola on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/826)

**Environment:**
OpenTAP 9.16.2

**Steps to reproduce:**
1. Add Parallel step into a plan
2. Add If verdict step as Parallel steps child
3. Set Parallel steps verdict into if verdict steps If parameter
4. Run the plan

**Actual result:**
Dead lock is produced.

**Expected result:**
If verdict should not allow verdict of it's own parent be placed as If parameter value. OpenTAP should not let to proceed into step 4.

**Other remarks:**
I raising this issue on behalf of colleague Teemu Luukkonen.
I used Parallel step as an example here as it's verdict is allowed in If verdicts If parameter. Not all OpenTAP test steps do.
But wanting to extend the limitation to all parents. Parent is not finished until all of it's childs are finished.

@witold wanted to be tagged into this. So that is now covered.

**Comment by tiberiumuntean21** [comment]
Fixed in OpenTAP 9.18.0-beta.7
![image](https://user-images.githubusercontent.com/98957694/167606547-71875690-1382-419a-bd34-f0f2732c15de.png)
