### ISSUE TITLE
Resolving dependencies does not respect semantic version

### ISSUE THREAD

**Issue by Denrask** [opentap/opentap#221]
Image can specify:
- Plugin A
  - Dependency OpenTAP ^9.15.2
- Plugin B
  - Dependency OpenTAP ^9.16.0-beta.12

Resolved OpenTAP is 9.16.0-beta.12 which is not semantically compatible with ^9.15.2.
Resulting OpenTAP should have been 9.16.x

![image](https://user-images.githubusercontent.com/18167872/150966030-28752308-f644-45a9-bb2d-4e1ba0a41434.png)

**Comment by rmadsen-ks** [comment]
In the case you mention:
```   
 Plugin A
        Dependency OpenTAP ^9.15.2
    Plugin B
        Dependency OpenTAP ^9.16.0-beta.12
```

According to our current logic this should resolve to OpenTAP 9.16.0-beta.12. This is because the resolver is conservative in regards to the hat-symbiol.
