### ISSUE TITLE
The `PluginManager` loads assemblies that cannot be loaded

### ISSUE THREAD

**Issue by StefanHolst** [opentap/opentap#230]
When loading all plugins and trying to get custom attributes it throws a FileNotFoundException

```cs
var assemblies = PluginManager.GetAllPlugins()
    .Select(x => x.Type.Assembly)
    .Distinct()
     .Where(x => x.GetCustomAttributes<MyExtension>().Any());
```

**Comment by alnlarsen** [comment]
We probably can't avoid loading incompatible assemblies, but we can handle the errors better.
