### ISSUE TITLE
Use tap.sh script in Linux/MacOS package

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#277]
We are currently bundling the binary executable 'tap' built for Linux in the MacOS package which does not work. The tap.sh script works on both platforms, so let's package that instead.

**Comment by jfaaborg** [comment]
@alnlarsen has this been fixed? if so can you provide a link to the pull request.

**Comment by alnlarsen** [comment]
This has been fixed by #281 It looks like we forgot to link the issue.
