### ISSUE TITLE
The Documentation has two links

### ISSUE THREAD

**Issue by ghost** [opentap/opentap#283]
**Environment:**

Google Chrome, 97.0.4692.99 64-bit

OpenTAP 9.16.2

**Steps to reproduce:**

1. Go to the opentap.io
2. Scroll to the “Getting Started” area
3. Click on Documentation button
4. Return to the opentap.io page
5. Access the Resources page from main menu
6. Click on Documentation button from “Useful links”

**Actual result:**

There are two links available for Documentation button:

https://docs.opentap.io/

https://doc.opentap.io/

![2022-02-08 14_17_42-](https://user-images.githubusercontent.com/98388827/153011081-3c9a3980-3a71-412c-81ca-bf0368649715.png)

![2022-02-08 14_18_20-](https://user-images.githubusercontent.com/98388827/153011108-76afd538-bff9-48f2-9f83-7b7a4e23d819.png)

**Expected result:**

There should be only one link for Documentation button

**Comment by alnlarsen** [comment]
@StefanHolst can you move this to the opentap-homepage repo?

**Comment by StefanHolst** [comment]
@bdirenzo-keysight I don't think we have a preference.

**Comment by StefanHolst** [comment]
@bdirenzo-keysight It seems we have some issues with the github pages CNAME. So only doc.opentap.io is working currently.

**Comment by bdirenzo-keysight** [comment]
All the links on OpenTAP.io point to doc.opentap.io now, so I think that's ok.
