### ISSUE TITLE
(Improvement) Returning to the opentap.io form repository page is not possible 

### ISSUE THREAD

**Issue by ghost** [opentap/opentap#287]
**Environment:**

Google Chrome, 97.0.4692.99 64-bit

https://opentap.io/

**Steps to reproduce:**

1. Access the opentap.io
2. Go to the “Resources” page
3. Click on the “View Package Repo” button
![2022-02-08 17_14_31-Resources _ OpenTAP](https://user-images.githubusercontent.com/98388827/153145573-0f364757-f3df-4ea2-9ad9-a644142c0fa9.png)

**Actual result:**

A new Repository page is opened

![2022-02-08 17_15_46-](https://user-images.githubusercontent.com/98388827/153145548-9a4b1450-28c7-4a9a-a18e-e077795b9edf.png)

**Expected result:**

The opentap.io menu must be added to the page or a homepage return button

![2-2022-02-08 17_15_46-](https://user-images.githubusercontent.com/98388827/153145607-35f532fd-db7b-4193-9b24-5fffd93a43f3.png)

**Comment by StefanHolst** [comment]
@bdirenzo-keysight No, we don't have any plans for this. Is this something we want?

**Comment by bdirenzo-keysight** [comment]
@StefanHolst I think it would be a nice to have feature.
