### ISSUE TITLE
Add SDK Template Support for VS 2022

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#3]
Originally filed December 03 2021 by Brennen DiRenzo on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/818)

https://devblogs.microsoft.com/visualstudio/visual-studio-2022-now-available/

**Comment by bdirenzo-keysight** [comment]
Are are starting to see some people migrate here, so this would be nice to update soon.

**Comment by witoldpiet** [comment]
Any updates on this?

@razvancoste , weren't you at some point in time working on a related issue?

**Comment by bdirenzo-keysight** [comment]
@AsgerIversen / @rmadsen-ks we are having more and more requests for this.

**Comment by witoldpiet** [comment]
Wasn't @frederikja163 working on this at some point in time?

**Comment by bdirenzo-keysight** [comment]
@AsgerIversen/ @rmadsen-ks / @alnlarsen where are we at on supporting this? It continues to repeatedly come up.

**Comment by alan-copeland-keysight** [comment]
We ran into an issue today where installing **VS 2022 installed .NET 7 SDK**, which broke VS2019's SDK templates... There was a complaint that the versions of the SDK and MSBuild were incompatiable. Uninstalled .NET 7 SDK through the VS 2022 installer partially fixed it, but then the VS2019 templates were still failing. Finally found that downgrading to .NET 6.1xx SDK fixed the issue (.NET 6.2xx+ SDK's are MORE incompatible with VS 2019. .NET 6.1xx just throws silent warnings but is functional).

All that to say, we need to update our SDK to support VS 2022 and make sure VS 2019 still works.

**Comment by sebastian-pop** [comment]
Starting OpenTAP (and SDK) 9.23 we only support VS 2022

**Comment by rmadsen-ks** [comment]
This has been implemented.
