### ISSUE TITLE
On mobile, the Subscribe text is not centered 

### ISSUE THREAD

**Issue by ghost** [opentap/opentap#308]
**Environment:**

Google Chrome, 98.0.4758.82 64-bit

https://opentap.io/

**Steps to reproduce:**

1. Access the opentap.io from mobile
2. Scroll to the “Sign up for our newsletter”
3. Check the “Subscribe” text

**Actual result:**

The Subscribe text is not centered

![2022-02-14 10_46_41-Home _ OpenTAP](https://user-images.githubusercontent.com/98388827/153832680-a1d3a660-07ad-41cf-be2c-c8b6fd602796.png)

**Expected result:**

The Subscribe text must be centered

![2022-02-14 10_46_41-Home _ OpenTAP-2](https://user-images.githubusercontent.com/98388827/153832717-4568620d-1109-4297-8e4d-dff8b4d98266.png)

**Comment by alnlarsen** [comment]
This does not belong to OpenTAP.
