### ISSUE TITLE
The thumbnail image of the “What’s happening” banner doesn’t keep the aspect ratio

### ISSUE THREAD

**Issue by ghost** [opentap/opentap#309]
**Environment:**

Google Chrome, 98.0.4758.82 64-bit

https://opentap.io/

**Steps to reproduce:**

1. Access the opentap.io
2. Scroll to the “What’s happening” banner
3. Check the thumbnail image of the article

**Actual result:**

The thumbnail image of the article doesn’t keep the aspect ratio

![2022-02-14 11_21_20-Home _ OpenTAP](https://user-images.githubusercontent.com/98388827/153836592-93a6128a-9ca0-4f78-acfa-7c1332b08780.png)

**Expected result:**

The thumbnail image of the article must keep the aspect ratio

![2022-02-14 11_23_46-Articles _ OpenTAP News](https://user-images.githubusercontent.com/98388827/153836615-962656a7-febe-49ba-852b-8674f1f5c961.png)

**Comment by alnlarsen** [comment]
This does not belong to OpenTAP.
