### ISSUE TITLE
(Improvement) Add some bullet points to the text

### ISSUE THREAD

**Issue by ghost** [opentap/opentap#313]
**Environment:**

Google Chrome, 98.0.4758.82 64-bit

https://opentap.io/

**Steps to reproduce:**

1. Access the opentap.io
2. Go to the About page
3. Check the “Who benefits” area

**Actual result:**

The benefits are written as a paragraph without bullet points.

![2022-02-14 11_48_04-About _ OpenTAP](https://user-images.githubusercontent.com/98388827/153842148-b99b2372-099c-4933-b898-755ca91d7af9.png)

**Expected result:**

The benefits must be written with bullet points.

**Other remarks:**

Keep consistency with the design for About and Join Us page. The About page has the “Who benefits” area, displayed with a white background.

![2022-02-14 11_48_24-Join Us _ OpenTAP](https://user-images.githubusercontent.com/98388827/153842186-b44fe1f3-14aa-48ee-b405-e8f6afac90b9.png)

**Comment by alnlarsen** [comment]
This does not belong to OpenTAP.
