### ISSUE TITLE
The OpenTAP project has some broken links on GitLab  

### ISSUE THREAD

**Issue by ghost** [opentap/opentap#319]
**Environment:**

Google Chrome, 98.0.4758.82 (Official Build) (64-bit)

https://gitlab.com/OpenTAP/opentap

**Steps to reproduce:**

1. Go to the gitlab.com/OpenTAP/opentap
2. Scroll to the “Readme” area

**Actual result:**

The link [https://opentap.io/download.html](https://www.opentap.io/download.html)  and “[PDF](https://opentap.io/docs/OpenTAP%20Developer%20Guide.pdf) for offline reading” redirect to a 404 page

![2022-02-16 10_38_18-OpenTAP _ OpenTAP · GitLab](https://user-images.githubusercontent.com/98388827/154227488-82b8c66d-d19f-4109-9588-47eedf6dc72d.png)

**Expected result:**

The links must work

**Other remarks:**

The issue also reproduces on GitHub

**Comment by heintz427** [comment]
Hi @alnlarsen. Can you tell me where this page/document is visible to the user? Looking through documents at https://doc.opentap.io, I am not seeing this page/document. Thanks!

**Comment by alnlarsen** [comment]
@heintz427 this page is only visible here: https://gitlab.com/OpenTAP/opentap

Since the top of the readme clearly states that the project has been moved to GitHub (here), I don't think it matters that the rest of the information is outdated.

**Comment by heintz427** [comment]
Closing this issue out... the content at https://github.com/opentap/opentap has been updated.
