### ISSUE TITLE
Downloading Contribution License Agreement (CLA) from CONTRIBUTING.md file doesn’t work  

### ISSUE THREAD

**Issue by ghost** [opentap/opentap#321]
**Environment:**

Google Chrome, 98.0.4758.82 (Official Build) (64-bit)

[gitlab.com/OpenTAP/opentap](gitlab.com/OpenTAP/opentap)

**Steps to reproduce:**

1. Access the [gitlab.com/OpenTAP/opentap](gitlab.com/OpenTAP/opentap)
2. Open the CONTRIBUTING.md file
3. Click on the “[here](https://opentap.io/docs/OpenTAP%20Contributor%20License%20Agreement%20v2.pdf)” button to download Contribution License Agreement (CLA)

**Actual result:**

The link redirects to a 404 page

![2022-02-16 10_58_30-opentap_CONTRIBUTING md at main · Keysight_opentap](https://user-images.githubusercontent.com/98388827/154231388-76f6c931-c425-4084-8bcf-3e7abbc4bb5b.png)

**Expected result:**

The link must work

**Other remarks:**

The issue also reproduces on GitHub

**Comment by heintz427** [comment]
07 Mar 2024: Updated \opentap\CONTRIBUTING.md to fix broken link. 
PR: https://github.com/opentap/opentap/pull/1463

**Comment by heintz427** [comment]
Issue fixed.
