### ISSUE TITLE
Examples: Failed to run install step 'tap.exe communityeditionpopup

### ISSUE THREAD

**Issue by razvancoste** [opentap/opentap#331]
**Environment:**

Windows 10, 64-bit

OpenTAP 9.17.0-rc.1
SDK 9.17.0-rc.1

**Steps to reproduce:**

1. Build Examples solution

[MSBuild 2022-02-18 09-26-39.txt](https://github.com/Keysight/opentap/files/8095021/MSBuild.2022-02-18.09-26-39.txt)
[SessionLog 2022-02-18 09-27-58.txt](https://github.com/Keysight/opentap/files/8095028/SessionLog.2022-02-18.09-27-58.txt)

**Actual result:**

![image](https://user-images.githubusercontent.com/98153555/154638649-c40117bc-0deb-42dd-bdfa-3c4fae583fa2.png)

(Please also attach a log file from %TAP_PATH%\SessionLogs\ that shows the issue when possible/relevant)

**Expected result:**

**Other remarks:**

**Comment by alnlarsen** [comment]
This belongs to KS8400.

@razvancoste can you move this?
