### ISSUE TITLE
API for expanding/collapsing test steps heirachies

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#332]
Based on user request. It would be helpful to be able to control the expand/collapse state from an API, and also save the state as a part of the test plan.

**Comment by sebastian-pop** [comment]
Implemented

![image](https://user-images.githubusercontent.com/97734470/171614690-b37e6cc3-f3a4-40d4-90be-88a29bda5739.png)

**Comment by razvancoste** [comment]
Checked using KS8400 9.17.4-beta.8

Test step hierachies remains saved when reloading test plan.
