### ISSUE TITLE
Installer properties details missing

### ISSUE THREAD

**Issue by ghost** [opentap/opentap#362]
**Environment:**

Windows 10, 64-bit

OpenTAP 9.17.0-rc.1

**Steps to reproduce:**

1. Right-click on OpenTAP 9.17.0-rc.1 installer 
2. Go to the Properties
3. Navigate to the Details tab

**Actual result:**

![2022-02-22 11_00_21-Settings](https://user-images.githubusercontent.com/98388827/155098005-d9198525-3e10-47db-a096-1ed4c0307dd2.png)

**Expected result:**

![2022-02-22 11_01_08-Settings](https://user-images.githubusercontent.com/98388827/155098138-1fee02af-7646-41e1-b536-52c5b2cd4c0b.png)

**Comment by alnlarsen** [comment]
@razvancoste I believe this was fixed i 9.17.1. Can you verify this?

**Comment by razvancoste** [comment]
@alnlarsen OpenTAP 9.17.2
![image](https://user-images.githubusercontent.com/98153555/158178034-cee0ba5d-e4d1-4344-b572-8dd57a48eff0.png)

**Comment by rmadsen-ks** [comment]
@razvancoste, I believe this issue belongs to the smartinstaller project. Can you move it there?

**Comment by razvancoste** [comment]
@rmadsen-ks there is an issue opened there.
