### ISSUE TITLE
.net 472: Windows Principal functionality is not supported on this platform

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#403]
When installing a system-wide package with .net framework this happens.

https://github.com/dotnet/standard/issues/1279

It seems this dependency is a part of .net framework and dotnet. 

So maybe we just need to not ship this dll:
![image](https://user-images.githubusercontent.com/24250062/156357062-56c99b1c-c34a-4e11-9857-fee688bd6ee2.png)

**Comment by alnlarsen** [comment]
Elevation works for me from the CLI and the Editor if I delete all instances of System.Security.Principal.Windows.dll from my OpenTAP install. Let's do that!

**Comment by alnlarsen** [comment]
This has been fixed in 9.17.4 by reverting to .NET Framework.

**Comment by sebastian-pop** [comment]
This must be verified when switching to .NET 6
