### ISSUE TITLE
Test execution fails when using Notify result listener

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#404]
**Steps**
1. Set Notify as a result listener
2. Run a test plan from CLI

**Actual Result**
Test plan is not executed. Errors
[SessionLogx 2022-03-02 16-32-09.txt](https://github.com/opentap/opentap/files/8170281/SessionLogx.2022-03-02.16-32-09.txt)

**Note**
Works when used in Editor. Problem is running from CLI

**Comment by rmadsen-ks** [comment]
I believe this was fixed by reverting tap.exe to .net framework.  Please reopen if the issue reappears.
