### ISSUE TITLE
Upgrade Newtonsoft to 12.0.3

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#445]
There is a DDOS vulnerability in Newtonsoft 12.0.2 which turns up in vulnerability scans for OpenTAP. It should be safe to upgrade to 12.0.3 which does not have this uvlnerability.

**Comment by tiberiumuntean21** [comment]
Fixed in OpenTAP version 9.18.0-beta.11
![image](https://user-images.githubusercontent.com/98957694/167834836-75788603-bc45-4e8f-ad0b-040dfb4d24b3.png)
