### ISSUE TITLE
Transitive dependency resolution bug

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#460]
# Problem

We have some serious issues related to dependency resolution particularly surrounding packages that use the 'any' version specifier. This has recently caused projects that use OpenTAP 9.17 and "Developer's System" to not build at all due to the SDK package resolving to an RC version which depends on an incompatible version of OpenTAP, which is problematic because this is a very common scenario. The same issue can easily arise in many different scenarios, and it is critical that we get this resolved. It is easy to construct the exact scenario where the issue arises:

Imagine an image which asks for a specific version of OpenTAP, and "Visual Studio SDK" in any version.

When we expand the dependency tree, we get something like this:

```
├── OpenTAP 9.17.2
│   └── OpenTAP 9.17.2
└── Visual Studio SDK Any
    └── Visual Studio SDK 1.2.4
        └── SDK Any
            └── SDK 9.17.3 RC
                └── OpenTAP ^9.17.3 RC
                    └── OpenTAP 9.17.3 RC
```

We ask for OpenTAP in exactly version 9.17.2, and we get 9.17.2. So far, so good.

Visual Studio SDK "Any" resolves to version 1.2.4. Ok. 

This adds a dependency on "SDK" in version 'Any', which (at the time of writing) resolves to "9.17.3 RC". Ok.

This adds a dependency on "OpenTAP ^9.17.3 RC", which is incompatible with the dependency on exactly 9.17.2 from the root! Not ok!

If our dependency resolver was clever, it would detect this issue and select "SDK 9.17.2" which is able to satisfy our dependency on OpenTAP 9.17.2, but it doesn't.

# Solution

The dependency resolver should be able to resume dependency resolution from an earlier stage when it gets stuck. 

This can add a significant overhead especially in cases where there is no way to satisfy all dependencies. Every new attempt to resolve dependencies will require new requests, potentially to several http repositories, so we need to be clever about how we resolve versions.

As Dennis suggested, it would be helpful if the http repository implemented a mechanism for getting all packages that depend on a given package, but regardless, OpenTAP must be able to resolve the issue without explicit repository support because we still need to be able to support older versions of the repository.

Consider the following dependency tree:

```
├── OpenTAP 9.17.2
│   └── OpenTAP 9.17.2
├── Visual Studio SDK CE Any
│   └── Visual Studio SDK CE 1.2.4
│       └── SDK Any
│           └── SDK 9.17.3 RC
│               └── OpenTAP ^9.17.3 RC
│                   └── OpenTAP 9.17.3 RC
└── Developer's System CE Any
    ├── Developer's System CE 9.17.1
    │   └── Editor CE Any
    │       └── Editor CE 9.17.1
    │           └── OpenTAP ^9.17.2
    │               └── OpenTAP 9.17.2
    ├── OpenTAP Any
    │   └── OpenTAP 9.17.2
    └── Visual Studio SDK CE Any
        └── Visual Studio SDK CE 1.2.4
            └── SDK Any
                └── SDK 9.17.3 RC
                    └── OpenTAP ^9.17.3 RC
                        └── OpenTAP 9.17.3 RC

```

In this case, there are several identical subtrees that occur multiple times in the dependency tree. Visual Studio SDK in version 'any' is a root dependency, but it is also a dependency of 'Developer's System'

During both resolutions of different versions of 'Visual Studio SDK', we are attempting to resolve the same version of 'SDK' which turns out to be incompatible. 

A naive solution to resuming dependency resolution from an earlier stage can easily add exponential complexity to an already slow operation, so we should take great care to detect when a subtree is already either resolved, or known to be unresolvable.

**Comment by Denrask** [comment]
Long term solution could be PackageRepository returning the information we need to take this informed decision: https://github.com/opentap/repository/issues/90

**Comment by alnlarsen** [comment]
Moving this to 9.18 as the solution to this issue is too complicated to resolve in 9.17. As a band-aid this particular instance of the problem with 'Developer's System' should be resolved in that package's dependency hierearchy.

**Comment by alnlarsen** [comment]
See #692 for a much simpler project which has the same issue, though that instance of the problem can probably be solved with a much simpler non-general solution

**Comment by alnlarsen** [comment]
In order to avoid hitting the repo a million times, we should probably query a local cache when we start resolving an image. The information we need is already supported by the HTTP repository's graphql API:

```sh
query () {
  local repo=$1
  local q='
  query Query { packages(version: "any") {
    name
    version
    dependencies
      { 
        name
        version
      }
    }
  }'
  curl -X POST "$repo/3.1/Query" -H "Accept: application/json" -sH 'Accept-encoding: gzip' -H "Content-Type: application/x-www-form-urlencoded" -d "$q" | gunzip > output.json
}
```

Let's make the super resolver!
