### ISSUE TITLE
Legacy Sweep Loop Range Can Iterate paramters of deleted steps

### ISSUE THREAD

**Issue by razvancoste** [opentap/opentap#481]
**Environment:**

Windows 10, 64-bit

OpenTAP 9.17.3
OpenTAP 9.16.4

**Steps to reproduce:**

1. Import/Open SweepLoopRange.TapPlan and delete Dialog step then run test plan  [SweepLoopRange.zip](https://github.com/opentap/opentap/files/8322462/SweepLoopRange.zip)
2. Create a new test plan with a sweep loop(range) and a Dialog step, add Timeout sweep parameter, then delete Dialog step and run the test plan

**Actual result:**

1. ![Animation](https://user-images.githubusercontent.com/98153555/159438282-0c3641ab-316d-4e50-957d-9e21607d0f1d.gif)

2. ![Animation](https://user-images.githubusercontent.com/98153555/159437847-91b67f60-0efd-478c-9492-cffb4b194bad.gif)

(Please also attach a log file from %TAP_PATH%\SessionLogs\ that shows the issue when possible/relevant)

**Expected result:**

After child step deletion, Sweep parameters should be cleared and error should be shown when test plan run.

**Other remarks:**

**Comment by rmadsen-ks** [comment]
We should check at run that child test steps exists with the selected parameters.

**Comment by razvancoste** [comment]
Fixed on 9.18.0-beta.33

![image](https://user-images.githubusercontent.com/98153555/169510235-53072632-ef2b-41c0-8fc9-1c8294ec8840.png)
