### ISSUE TITLE
Update release notes to 9.17 on opentap.io

### ISSUE THREAD

**Issue by razvancoste** [opentap/opentap#483]
**Environment:**

**Steps to reproduce:**

![image](https://user-images.githubusercontent.com/98153555/159889871-cac18814-c6fa-4f85-b07e-627df07062b3.png)

![image](https://user-images.githubusercontent.com/98153555/159889934-247669d3-c058-4eb9-91fe-6ede8ec9c287.png)

**Actual result:**

Release notes 9.16

(Please also attach a log file from %TAP_PATH%\SessionLogs\ that shows the issue when possible/relevant)

**Expected result:**

Release notes 9.17

**Other remarks:**

**Comment by alnlarsen** [comment]
@jfaaborg do you know the status on this? Do we even have 9.17 release notes?

**Comment by jfaaborg** [comment]
We have not migrated the release note utilities from Gitlab. In GitHub it is put together a bit differently and can be found here:  https://github.com/opentap/opentap/releases 

We will need to figure out if that is the best format going forward (note it show pull request and not issues) or we should migrate our utility and then let that generate notes that can be put on doc.opentap.io.

**Comment by alnlarsen** [comment]
This should be a manual task until we have a tool that can automate it.

**Comment by jfaaborg** [comment]
I think it looks okay (https://github.com/opentap/opentap/pull/579/files?short_path=fadece2#diff-fadece206ff09c97833102c1e735767beb8fcc20b5cd570356ebab2494304d30)  @AsgerIversen will you merge it - it seems like the PR needs to be rebased.
