### ISSUE TITLE
Parameterization, default group should not insert "Parameters"

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#49]
Originally filed January 18 2021 by david-wsd on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/518)

When parameterizing, OpenTAP is inserting a group called "Parameters" to the default group. Is this technically required, or beneficial in some scenario? We delete it every time. If it's not a problem, I propose removing the auto-insertion of the "Parameters" group.

**Comment by rmadsen-ks** [comment]
I think the current behavior (Adding "Parameters") has not given issues and helps people to understand the test plan. In the end it is a trade off. We can reopen this issue by request from the community.
