### ISSUE TITLE
Add CI/CD documentation for Github

### ISSUE THREAD

**Issue by bdirenzo-keysight** [opentap/opentap#494]
Currently we only have Gitlab
![image](https://user-images.githubusercontent.com/78063177/160426440-6fd07e3d-39ed-48cb-9932-a5702944b43d.png)

**Comment by rmadsen-ks** [comment]
We need to have an example of how to create a CI pipeline that builds and publishes a TapPackage.

**Comment by rmadsen-ks** [comment]
Lets add a section about Github, what is stated about Gitlab is probably still true.
