### ISSUE TITLE
Forgotten development placeholder on https://opentap.io/about#ecosystemPartners

### ISSUE THREAD

**Issue by g-galante** [opentap/opentap#497]
![image](https://user-images.githubusercontent.com/102026043/161064800-e648bf7a-8eac-4836-9fcc-7cb96ba5b1d5.png)

The *collection* alone on its own line after:

> The OpenTAP ecoystem grows stronger day by day from the contributions of Original Equipment Manufacturers (OEMs), test and measurement vendors, integrators, and independent Software Vendors (ISVs) including:

on https://opentap.io/about#ecosystemPartners looks a lot like a forgotten development placeholder for the collection of partners.

Shouldn't *independent* in the quotation above be capitalized (*Independent*) as the two following words in the acronym?

In addition, I'm not completely sure whether the two projects: [5G-VINNI](https://www.5g-vinni.eu/) and [5Genesis](https://5genesis.eu/), co-funded by the European Union's [Horizon 2020](https://wayback.archive-it.org/12090/20220124075100/https:/ec.europa.eu/programmes/horizon2020/) research and innovation funding program, actually belong there, at least according to the definition quoted above.

Maybe it would be better to either remove them or to update the preceding partner definition to include them.

**Comment by alnlarsen** [comment]
Hi g-galante, thanks for bringing this to our attention.

@bdirenzo-keysight can you take a look at this?

**Comment by bdirenzo-keysight** [comment]
@g-galante where does this link to for you? I see the start of "our ecosystem partners". Members from 5G-VINNI and 5Genisis both have signed the CLA and contributed to OpenTAP, so we definitely want to include them. I'll update the description wording to make it more generic.

**Comment by g-galante** [comment]
I later stumbled upon https://news.opentap.io/opentap-community-ecosystem-members:
> Since its inception, the OpenTAP project has been conceived as an ecosystem, including the collaborative efforts of – hardware manufacturers, software vendors, system integrators, research labs, universities and other organizations. ​

which is a little bit wider, and may be better suited, because it includes *research labs, Universities and other organizations*.
Anyway, feel free to leave everything as it is right now ;)

**Comment by bdirenzo-keysight** [comment]
Updated wording
