### ISSUE TITLE
Meaningless sentence on https://opentap.io/resources

### ISSUE THREAD

**Issue by g-galante** [opentap/opentap#498]
![image](https://user-images.githubusercontent.com/102026043/161074221-c6ae08e0-e5b4-46e0-8f1c-e92d10eb71f8.png)

The emphasized sentence below from the *Learn more* Section on https://opentap.io/resources doesn't make much sense:
> If you are looking for more specifics take a look at our YouTube channel that walks through various aspects of OpenTAP. *We may many examples as well to show different features of the SDK.* Still can't find what you are looking for? Ask about it on our forum.

please, fix it.

**Comment by bdirenzo-keysight** [comment]
Fixed
