### ISSUE TITLE
Improve --out of package create action to allow specifying a directory

### ISSUE THREAD

**Issue by Denrask** [opentap/opentap#502]
In the CLI command `tap package create` you are able to specify `--out <file>`, which allows you to set the exact package file name. However, when not specifying `--out`, the command will create the filename in the format of `<package-name>.<version>.TapPackage`.

In CI pipelines we often create a package and publish it afterwards using the CLI, it would be nice if you were able to specify a directory as an argument to `--out`. Example: `tap package create MyPackageXml.xml --out C:/Temp` and the result would be a TapPackage at `C:/Temp/<package-name>.<version>.TapPackage`

**Comment by rmadsen-ks** [comment]
Maybe we should also add OS and architecture: `<package-name>.<version>.<os>-<arch>.TapPackage`
e.g: `OpenTap.9.17.0.linux-x64.TapPackage`

**Comment by rmadsen-ks** [comment]
What determines if a --out argument is a directory or file is the trailing slash/backslash.
