### ISSUE TITLE
Image Deploy does not clean up after failed deployment

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#507]
If a package fails to install during an image deployment, only the package which failed to install is uninstalled. 

When deploying to a new directory which did not previously exist, the entire directory should be removed.

**Comment by rmadsen-ks** [comment]
@alnlarsen, can you specify more clearly how to reproduce, what you see and what you expected.

**Comment by Denrask** [comment]
@alnlarsen, can you specify more clearly how to reproduce, what you see and what you expected.

**Comment by alnlarsen** [comment]
I experienced this with the smart installer where the installer failed to deploy a new installation to a clean directory, and I was left with a partial install.

This was some time ago, and the smart installer issue is difficult to reproduce. I will add more details here if the issue arises again.

**Comment by alnlarsen** [comment]
I will reopen this if the problem arises again
