### ISSUE TITLE
tap run: no errors when specifying invalid external parameter values

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#508]
When specifying an invalid value for an external parameter, the parser continues without logging any warnings (even at the debug level)

1. Create a testplan
2. Add a delay step
3. parameterize Time Delay on the test plan
4. `tap run delay.TapPlan -e "Parameters \ Time Delay=abc"`

Observe that Time Delay is left at the default value, and there are no warnings

**Comment by rmadsen-ks** [comment]
This logic is handled by the ExternalParameterSerializer class. It should create an error if the value is not valid for the parameter.

**Comment by frederikja163** [comment]
Forgot to link the corresponding PR #524

**Comment by rmadsen-ks** [comment]
Great, sounds like we can close this!

**Comment by tiberiumuntean21** [comment]
Issue is fixed. Tested on OpenTAP 9.18.0-beta.16

![image](https://user-images.githubusercontent.com/98957694/168226634-b3eb2b86-f153-404d-91d2-f9bd2b3e60de.png)
