### ISSUE TITLE
Warnings when installing a system wide package

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#509]
Steps:

`tap package install "Keysight Fixed License Manager"`  

- Log: [SessionLog 2022-04-10 23-56-30.txt](https://github.com/opentap/opentap/files/8461720/SessionLog.2022-04-10.23-56-30.txt)
- Warning     ; Could not find OpenTAP in C:\ProgramData\Keysight\Test Automation.

`tap package install "PathWave License Manager"`  

- Log: [SessionLog 2022-04-10 23-58-11.txt](https://github.com/opentap/opentap/files/8461732/SessionLog.2022-04-10.23-58-11.txt)
- Warning     ; Selected package PathWave License Manager for Windows, x64 is incompatible with the host platform Windows, AnyCPU.
- Warning     ; Package 'PathWave License Manager' depends on 'OpenTAP' which will not be installed.

All these `subprocess` messages, are they necessary to be displayed? Maybe these should be debug messages

![image](https://user-images.githubusercontent.com/97734470/162685019-f36c26e1-f7a8-47cd-a56d-630f1eb364c7.png)

**Comment by rmadsen-ks** [comment]
I have noticed something similar. We need to fix this.

**Comment by razvancoste** [comment]
9.18.0-beta.19

No warning and no subprocess messages.

![image](https://user-images.githubusercontent.com/98153555/168613752-846cc26a-f62b-4c09-b5c2-f1a7dfefeef2.png)
