### ISSUE TITLE
Improve UnitTest RunParseTest

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#527]
The current RunParseTest unit test starts up several sub processes in order to verify the behavior of external parameters.

It is slow and flaky and when a problem occurs it can be hard to understand what went wrong.

This test should be improved by testing in a simpler way and if it tests multiple things, maybe split it into more tests

**Comment by frederikja163** [comment]
For now i have fixed the unittest by adding the correct dependencies to the project. It seems like this has fixed the issue for now.

This was done as part of #524 to make is pass so it can be merged.
