### ISSUE TITLE
Cannot install a system wide package on Ubuntu

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#528]
**Describe the bug**
Install fails for "PathWave License Manager" on Ubuntu

**To Reproduce**
1. `tap package install "PathWave License Manager"`

**Actual  behavior**
Installation fails.
I am being asked for sudo password

**Expected behavior**
PWLM should be installed

**Screenshots**
Log: [SessionLog 2022-04-29 10-49-04.txt](https://github.com/opentap/opentap/files/8589120/SessionLog.2022-04-29.10-49-04.txt)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - OpenTAP Version 9.17.4

**Comment by alnlarsen** [comment]
PWLM is not supported on Linux, (I think someone released the Windows version on Linux accidentally) but the exception looks like a general error related to installing system-wide packages.

**Comment by alnlarsen** [comment]
This seems to occur because we try to place a lock on the file `/usr/share/Keysight/Test Automation/.lock` which fails if the containing directory does not already exist. We should create this directory if it doesn't.

**Comment by razvancoste** [comment]
RHEL 8:

**Comment by sebastian-pop** [comment]
Fix verified on 9.18.0-beta.13

Lock issue has been fixed and PWLM is actually installed on Ubuntu. And it starts
