### ISSUE TITLE
Retrying repo downloads 60 times in a loop is excessive

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#529]
See the offending code here: https://github.com/opentap/opentap/blob/29081f8230af5ab025e9846871659c93622af3e3/Package/Repositories/HttpPackageRepository.cs#L132

This retry code is almost never executed. I experienced it in a local environment with an alpha build of the HTTP repository (I suspect) because the repository claimed to have a package, but an exception was triggered in the repo when I tried to download said package.

In any case, retrying 60 times here seems excessive, and while this behavior likely doesn't affect anyone, the code could use some cleanup.

**Comment by sebastian-pop** [comment]
I can reproduce the 60 retry issue by: starting a download from the internal repo and turning off my VPN. OpenTAP will retry 60 times to download the package.

The same scenario with the OpenTAP 9.18.0-beta.10 will have no retries at all. Log: 
[SessionLog 2022-05-11 14-57-52.txt](https://github.com/opentap/opentap/files/8669656/SessionLog.2022-05-11.14-57-52.txt)


![image](https://user-images.githubusercontent.com/97734470/167844796-dfb398ab-b87b-4027-9d6e-85bfc76b6b32.png)


@rmadsen-ks what do you think?

**Comment by sebastian-pop** [comment]
The 60 retries has been removed
