### ISSUE TITLE
Update latest version of OpenTAP on official website

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#54]
Originally filed February 16 2021 by Razvan Coste on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/565)

**Environment:**

Windows 10, 64-bit

**Steps to reproduce:**

**Actual result:**

![image](https://gitlab.com/OpenTAP/opentap/uploads/85ca6085147886bf23d4cf6f8113c522/image.png)

![image](https://gitlab.com/OpenTAP/opentap/uploads/0abd2eca3ac913c545b618a0cdb81220/image.png)

(Please also attach a log file from %TAP_PATH%\SessionLogs\ that shows the issue when possible/relevant)

**Expected result:**

![image](https://gitlab.com/OpenTAP/opentap/uploads/2debdf76c2b7d79da0fda6faaea3e437/image.png)

**Other remarks:**

**Comment by rmadsen-ks** [comment]
This has been updated.
