### ISSUE TITLE
Consistent installer failure (because of OS language?)

### ISSUE THREAD

**Issue by keysie** [opentap/opentap#548]
I tried installing OpenTAP 9.17.4 and 9.17.3 on multiple different windows machines using the the released *.exe installers. Installation of .NET 6 works as expected on all machines that didn't yet have it installed. All computers run fully patched Windows 10 in German. All attempts of installation fail with the same error message regarding permissions. The best translation of the error message I could find goes like this: "Some or all Identity references could not be translated". Since I am running the installer as Administrator with full privileges and have even tried different source- and target locations on each system, I am now assuming there is an issue with translated user names (e.g. "Everyone" equals "Jeder" in German).

![Screenshot 2022-05-09 175114](https://user-images.githubusercontent.com/12133964/167448348-f4ff0f7b-cd01-4f80-babb-5cfbed30237b.jpg)

**Comment by alnlarsen** [comment]
Someone also reported this on the forum with a German Windows system. Your assumption about translated names sounds likely. I know the installer writes some registry keys, so there could be localization issues. @StefanHolst can you take a look at this?

**Comment by razvancoste** [comment]
@alnlarsen 

**Reproduced** on Windows 10 (consumer editions) C version 21H2 (updated April 2022) - German version with **OpenTAP** **9.17.4**

**Cannot reproduce** on Windows 10 (consumer editions) C version 21H2 (updated April 2022) - German version with **OpenTAP 9.18.0-alpha.8.1**

Also when installing again the alpha installer i get the error below.
![image](https://user-images.githubusercontent.com/98153555/167799834-40ec448f-e51c-44bc-bf6f-78bbaf9e48d6.png)

**Comment by alnlarsen** [comment]
@keysie thanks a lot for verifying that it works! We will not make another 9.17.x installer, but at least the 9.18 installers should work ⭐

**Comment by keysie** [comment]
@razvancoste Cannot verify the problem you mentioned on my system. Repeated installs with the same alpha-installer work fine for me. However, when uninstalling via the control panel, I get the following error upon complete uninstall:

![Screenshot 2022-05-11 125921](https://user-images.githubusercontent.com/12133964/167834565-a7535ae9-fd1a-4d2d-8884-155b65434179.jpg)

After the uninstall the OpenTap folder is not completely removed.

**Comment by razvancoste** [comment]
@alnlarsen 
After install 
![image](https://user-images.githubusercontent.com/98153555/167844541-339b2f8d-7c33-4ebf-ad3c-2547d1cb0654.png)

After uninstall
![image](https://user-images.githubusercontent.com/98153555/167845197-98d10263-b6de-4c61-88cd-d9e75a710c61.png)

**Comment by razvancoste** [comment]
No installer failure anymore.
9.18.0-beta.12

Uninstall issue should be opened separately.
