### ISSUE TITLE
tap package install of file-like objects

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#551]
Sometimes it is pretty obvious that the user is trying to install a tap package from a file:
```tap package install Test.TapPackage```

Still in this case we ask the package repository for a package named Test.TapPackage, which does not exist.

When a package name ends with TapPackage we should just assume that it is always a file and throw a FileNotFoundException instead of asking the package repositories.

**Comment by tiberiumuntean21** [comment]
Issue is fixed on 9.18.0-beta.10

![image](https://user-images.githubusercontent.com/98957694/167840416-ee07dc03-d37a-4a78-8976-815c938ddc2f.png)

@rmadsen-ks  Wondering if the first sentence, the one with downloading the package, is correctly displayed for the user. Meaning that he tries to install a local package, not from repository, which means no download is necessary.
