### ISSUE TITLE
tap package install cannot be stopped when running in a test plan

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#555]
Run the following Run Program step:

![image](https://user-images.githubusercontent.com/24250062/167629321-0b17162c-2165-4c2a-a3de-e2c51301b319.png)

Observer that the test plan never completes. If Abort is hit, the test plan will also not stop.

That is because the actually running process is a child-child process which is not reached with Process.Kill()

**Comment by tiberiumuntean21** [comment]
Issue is fixed on OpenTAP 9.18.0-beta.10

![image](https://user-images.githubusercontent.com/98957694/167865850-2cb9cbd8-5d65-413b-a92b-df4edadc58c6.png)
