### ISSUE TITLE
Package install: Confusing error message when a package dependency is not in specified repositories

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#563]
If you install e.g. `Editor` and specify a local file directory as the repository, and you don't have all of its dependencies in the same repository, the error message you get is a null reference exception with no mention of the dependency conflict.

The actual error message should say that the dependency could not be resolved from the specified repositories.

**Comment by tiberiumuntean21** [comment]
Issue is fixed on OpenTAP 9.18.0-beta.16

![image](https://user-images.githubusercontent.com/98957694/168025517-9df5c4de-5b50-4f77-9069-3f813c6524c8.png)
