### ISSUE TITLE
Nuget package: load opentap bug

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#584]
When building with the latest beta nuget package, this error occurs when installing packages: `OpenTap.targets(94,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'OpenTap, Version=9.4.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

It looks like we are not loading the OpenTAP assembly correctly.

**Comment by razvancoste** [comment]
Verified in 9.18.0-beta.29

![image](https://user-images.githubusercontent.com/98153555/169033366-7526571e-0a4b-44d2-a8b8-aac2b19ef1bc.png)
