### ISSUE TITLE
Comments on the "Open Source in Test Automation v3" white paper available on https://opentap.io/about

### ISSUE THREAD

**Issue by g-galante** [opentap/opentap#587]
The attached [Open-Source-in-Test-Automation-v3.pdf](https://github.com/opentap/opentap/files/8708404/Open-Source-in-Test-Automation-v3.pdf) document has several spots that require further attention:

- [ ] On page 1, the white paper subtitle is:
  > The Open Source Path to Effortless Automation

  whereas the page footer, displayed from page two onwards is:
  > OpenTAP – The open source path to effortless automation

  consider aligning the capitalization.

- [ ] On page 3, the Section heading:
  > Situation analysis – test and measurement marketplace

  is the only one in the document not capitalized.

- [ ] The first sentence of that Section:
  > The test and measurement industry constitutes a large and very diverse market, expected to grow
  from USD 27.7 billion in 2021 to USD 33.3 billion by 2026.

  is almost identical to the first sentence of the next paragraph, on top of page 4 (emphasis added):
  > The test and measurement equipment market are expected grow at a CAGR of 3.7%
  from $27.7B in 2021 to `#`33.3B in 2026.

  If you decide to keep both:
  - A choice should be made between the use of *USD* and *$* as a currency symbol, and, if you opt for the latter, fix the *#* in the second quotation above.
  - A decision should also be made as to whether using *B* or *billion* as a multiplier.

- [ ] At the end of page 3, the red-highlighted sentence from *Frost and Sullivan* seems more appropriate on page 5, where it is actually quoted in the main text.

- [ ] Footnote 3 (on page 5) incorrectly references *Markets and Markets* instead of *Frost and Sullivan*. The correct reference is in footnote 2 (on page 3).

- [ ] Just before footnote 3, one would expect a quotation between inverted commas to be verbatim, but this is not the case, because [the original text reads](https://www.frost.com/frost-perspectives/asset-management-and-integrated-service-delivery-expansion-traditional-business-models-tm-market/):
  > It is not test equipment vs. test equipment anymore. No longer can test equipment focus on hardware alone. Instead, there is a potential focus on platform and ecosystem. There is a need to develop a platform-centric business model that effectively integrates hardware, software analytics, and services.

- [ ] On top of page 5:
  > growth include Automotive, Communications (5G and I7OT)

  consider replacing *I7OT* with *IoT*.

- [ ] At the beginning of page 15, the red-highlighted sentence seems to belong to page 16, where it is included in the main text.

- [ ] On page 15:
  > provides an equally apt option for use in Commercial Test Systems, as well as in green fields

  is the capitalization of *Commercial Test Systems* needed?

- [ ] On page 15 (emphasis added):
  > rely on ad hoc test executives *with* face challenges to interoperability and maintainability

  consider replacing *with* with *which*.

- [ ] On page 15:
  > **Commercial Test** – users and integrators of legacy commercial test executives, where

  consider replacing **Commercial Test** with **Commercial Test Systems**.

- [ ] On page 16, consider replacing *member companies* in:
  > As of July 2021, the OpenTAP ecosystem highlights the member companies below:

  with the ecosystem definition given in the piece of news linked at the bottom of the page https://news.opentap.io/opentap-community-ecosystem-members/:

  > Since its inception, the OpenTAP project has been conceived as an ecosystem, including the collaborative efforts of – hardware manufacturers, software vendors, system integrators, research labs, universities and other organizations.

  as also discussed in issue https://github.com/opentap/opentap/issues/497#issuecomment-1087626805.

- [ ] On page 18:
  > Documentation: doc.opentap.io

  `doc.opentap.io` incorrectly links to https://gitlab.com/OpenTAP/opentap instead of https://doc.opentap.io.

  It would also be useful to expose the scheme of the five URLs given in that Section, e.g.:
  > Documentation: https://doc.opentap.io

- [ ] Last line on page 21: consider transforming *www.opentap.io* in a link to https://www.opentap.io.

- [ ] On page 22, consider adding a period after *continually growing*.

- [ ] The capitalization  of *Open Source* seems inconsistent and, very often, you can find *open source* as well.

- [ ] The same also applies to *Test and Measurement*, *Aerospace & Defense*, *Automotive*, *Cloud*, *Communications*, *Telecommunications*.

- [ ] The glossary on page 23 contains a few acronyms that are not used in the white paper such as AMX, FOSS, GPIB, OSS, SPICE, TSC, but, on the other hand, does not include a lot of the acronyms found in it, such as: OpenTAP, IT, 5G, IoT, SDN, ICT, IBM, UNIVAC, NCR, ISP, CNCF, IVI, ADAS, 4G, 3G, NAS, AI, ML, DevOps, DevSecOps, MIT, GNU, APLv2, BSD, IP, IVI Foundation, MPLv2, API, GUI, UI, SQL, CSV, HTML, HTTP, PHP, SDK, REST.

**Comment by bdirenzo-keysight** [comment]
@bilzinho is this something you could look at?

**Comment by bilzinho** [comment]
I will do an update to the WP based on the comments/review.  I am not sure how some of these issues made their way into the copy.  Passed through too many hands, I guess.  On it.

**Comment by bdirenzo-keysight** [comment]
Fixed with v4 of whitepaper
