### ISSUE TITLE
`tap package download` interrupted download does not resume

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#592]
After this fix https://github.com/opentap/opentap/issues/529 , the download no longer resumes.

**Steps**
1. `tap package download "PathWave License Manager" -f -r packages.opentap.keysight.com`
2. Disconnect the VPN - > confirm download progress has stopped but the action is still ongoing
3. Connect the VPN - > confirm issue, download is not resumed

There is also no information in the log if there are retries to download.

**Comment by razvancoste** [comment]
Verifed using 9.18.0-beta.36

Stopped the VPN 2 times:

![image](https://user-images.githubusercontent.com/98153555/169782985-258982c2-61b2-4ba8-a638-09bf38ebb802.png)
