### ISSUE TITLE
Virtual Interface Implementations

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#6]
Originally filed November 07 2019 by Rolf Madsen on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/47)

Currently it is supported to have a test step with a settings that refers to another test step of a specific type. It is not possible to specify a test step that implements two specific types (unless one is a subtype of the other). I suggest we implement some system to support something I call virtual interfaces:

Here is an example of how it should be used:
```cs
    public class VirtualInterface : Attribute
    {

    }

    public interface InterfaceA
    {
        void MethodA();
    }

    public interface InterfaceB
    {
        void MethodB();
    }

    // Nobody actually implements this
    // objects that are InterfaceA and InterfaceB virtually implements
    // MyVirtualInterface
    [VirtualInterface]
    public interface IMyVirtualInterface : InterfaceA, InterfaceB
    { /* Empty implementation */}

   class StepWithVirtualInterfaceProperty : TestStep{
      // only steps that are InterfaceA and InterfaceB can be inserted here
      // It OpenTAP uses some runtime magic to make something that satisfies IMyVirtualInterface.
      public IMyVirtualInterface AAndB {get;set;}; 
   }

```

This can mostly be done inside an IAvailableValuesAnnotation, but some serializer plugin also has to be made.

In dotnet core 3.0, System.Reflection.Emit can be used, but for dotnet standard 2.0, we have to use roslyn. Otherwise the first step could also be a way to define the wrapper object that implements both interfaces manually. This would probably not be too much additional work.

**Comment by rmadsen-ks** [comment]
lets discuss this in 9.26

**Comment by rmadsen-ks** [comment]
After deliberating this over some time I've come to the conclusion that the added complexity does not justify the added flexibility.
