### ISSUE TITLE
Wrong error message when canceling elevated installs

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#603]
Clicking 'no' in the UAC dialog for an elevated install will cause an error log saying the download failed due to a network error. This should result in a 'User cancelled' info log.

**Comment by razvancoste** [comment]
Using OpenTAP 9.17.4

![image](https://user-images.githubusercontent.com/98153555/171681375-54382c4e-f6d3-4da5-b084-060ceecad002.png)

Using OpenTAP 9.18.0-beta.47

![image](https://user-images.githubusercontent.com/98153555/171682358-0fa16746-e229-484c-ab3f-60322d9ffcab.png)
