### ISSUE TITLE
TypeData.CanCreateInstance has invalid value for ValueTypes

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#610]
Every ValueType can be instanced using the default constructor, but our plugin searcher does not correctly determine if an instance can be created.

This can give issues if the user wishes to create a `List<KeyValuePair<string,string>>` because KeyValuePair is a value type.

This mostly occurs because of the order in which we discover type references. In some cases the opentap dll is loaded before the mscorlib dll and in this case the ValueType base class cannot be determined before later. 

The only way to determine if something is a ValueType is by looking at the baseclass.

**Comment by Denrask** [comment]
Linked to #607, which would solve this, according to Rolf.
