### ISSUE TITLE
 CliAction has thrown an exception - download --force not working

### ISSUE THREAD

**Issue by tiberiumuntean21** [opentap/opentap#614]
**Environment:**
Windows 10, 64-bit
OpenTAP 9.18.0-alpha.1.1

**Steps to reproduce:**
1. Run the follwing command: tap package download RemoteSignTool -r "packages.opentap.keysight.com" -f

**Actual result:**
CLIAction error is thrown and the package is not downloaded

![image](https://user-images.githubusercontent.com/98957694/170682119-2fd01a7e-9913-4a50-91fc-d8dc7e505c89.png)

**Comment by Denrask** [comment]
You have a typo, as the name is "RemoteSigntool" and not "RemoteSignTool" :)

![image](https://user-images.githubusercontent.com/18167872/170980958-098d2c3e-57c3-4da3-9714-31bb5328e37e.png)

This relates to #357.
