### ISSUE TITLE
"PackageName exists in cache:..." printed out twice

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#623]
![image](https://user-images.githubusercontent.com/24250062/171176003-92e5ae2b-545d-4da0-9a3e-a97eebb36ce9.png)

**Comment by tiberiumuntean21** [comment]
Issue is fixed. Tested on OpenTAP 9.18.0-beta.47

![image](https://user-images.githubusercontent.com/98957694/171814394-c628eaa2-ec76-4fbc-bf9b-7751026c0432.png)
