### ISSUE TITLE
DMM Test Steps not installed after choosing Ignore

### ISSUE THREAD

**Issue by tiberiumuntean21** [opentap/opentap#625]
**Environment:**
Windows 10, 64-bit
OpenTAP 9.18.0-rc.1

**Steps to reproduce:**
1. Run the following command: tap package install "DMM Test Steps" -r "http://packages.opentap.keysight.com/" -version 2.0
2. Choose Ignore

**Actual result:**
DMM Test Steps is not installed even if Ignore action has been chosen

![image](https://user-images.githubusercontent.com/98957694/171191702-5975711f-1b66-43d6-8c6e-0833316fe16b.png)

**Comment by alnlarsen** [comment]
Reproduced on 9.17.4
