### ISSUE TITLE
Add elevation prompt when uninstalling system-wide packages

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#627]
In 9.17 we added an elevation prompt when installing system-wide packages, but we didn't add one when uninstalling them again. This means that a user must now manually elevate a shell or package manager before uninstalling system-wide packages. This shouldn't be that complicated to implement.

**Comment by sebastian-pop** [comment]
@alnlarsen implement this for both Windows and Linux

**Comment by sebastian-pop** [comment]
@alnlarsen Elevation prompt has been added for uninstall, but the actual applications are not uninstalled

Keysight Fixed License Manager install logs: 
[SessionLog 2023-10-04 11-52-08.txt](https://github.com/opentap/opentap/files/12801415/SessionLog.2023-10-04.11-52-08.txt)
[SessionLog 2023-10-04 11-52-06.txt](https://github.com/opentap/opentap/files/12801416/SessionLog.2023-10-04.11-52-06.txt)
[SessionLog 2023-10-04 11-52-05.txt](https://github.com/opentap/opentap/files/12801417/SessionLog.2023-10-04.11-52-05.txt)

Keysight Fixed License Manager uninstall logs: 
[SessionLog 2023-10-04 11-53-27.txt](https://github.com/opentap/opentap/files/12801428/SessionLog.2023-10-04.11-53-27.txt)
[SessionLog 2023-10-04 11-53-28.txt](https://github.com/opentap/opentap/files/12801429/SessionLog.2023-10-04.11-53-28.txt)
[SessionLog 2023-10-04 11-53-29.txt](https://github.com/opentap/opentap/files/12801430/SessionLog.2023-10-04.11-53-29.txt)

PathWave License Manager install logs: 
[SessionLog 2023-10-04 11-54-25.txt](https://github.com/opentap/opentap/files/12801463/SessionLog.2023-10-04.11-54-25.txt)
[SessionLog 2023-10-04 11-54-28.txt](https://github.com/opentap/opentap/files/12801464/SessionLog.2023-10-04.11-54-28.txt)

PathWave License Manager uninstall logs: 
[SessionLog 2023-10-04 11-58-28.txt](https://github.com/opentap/opentap/files/12801470/SessionLog.2023-10-04.11-58-28.txt)
[SessionLog 2023-10-04 11-58-29.txt](https://github.com/opentap/opentap/files/12801471/SessionLog.2023-10-04.11-58-29.txt)
[SessionLog 2023-10-04 11-58-30.txt](https://github.com/opentap/opentap/files/12801472/SessionLog.2023-10-04.11-58-30.txt)

**Comment by alnlarsen** [comment]
@sebastian-pop I can reproduce this. After uninstalling, PWLM remains installed. I don't think this is related to OpenTAP's elevation implementation though.
