### ISSUE TITLE
Multi-Selecting list-types is not working

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#628]
Currently an exception is thrown if two test steps are selected and they have a list of editable items.

Since out parameter system can support this, we should also be able to support it for multi-select.

**Comment by razvancoste** [comment]
Verified using OpenTAP 9.18.0-beta.47

![image](https://user-images.githubusercontent.com/98153555/171685209-ec0e15af-8af1-4e11-b9a1-c1aef81710d4.png)
