### ISSUE TITLE
Unhandled GUI error when editing two Read-Only List Example test steps

### ISSUE THREAD

**Issue by tiberiumuntean21** [opentap/opentap#640]
**Environment:**
Windows 10, 64-bit
OpenTAP 9.17.4

**Steps to reproduce:**
1. Have Examples package built and installed
2. Add 2 Read-Only List Example test steps
3. Select both and click on Edit button right next to Elements

**Actual result:**
Unhandled GUI error

![image](https://user-images.githubusercontent.com/98957694/172436977-6e4a0d53-c546-43e8-aa93-ebdaffdd1853.png)

Session log file - [SessionLog 2022-06-07 19-40-01.txt](https://github.com/opentap/opentap/files/8855049/SessionLog.2022-06-07.19-40-01.txt)

**Comment by rmadsen-ks** [comment]
@sebastian-pop, can you verify this issue?

**Comment by sebastian-pop** [comment]
@rmadsen-ks This has been fixed. Verified on OpenTAP/SDK 9.18.4
