### ISSUE TITLE
`DateTime` fields are not handled properly by OpenTAP GUI

### ISSUE THREAD

**Issue by janandries** [opentap/opentap#659]
### Description

DateTime fields that are changed by the user in the GUI, do not update the underlying variable, rendering these GUI elements unusable.

### Environment

Windows 10.0.19044 Build 19044, 64-bit
Test Automation 9.17.4+5e508f08 (64-bit) Official Release

### To reproduce

- Open the OpenTap Test Automation with the SDK Examples compiled.
- Go to Settings > Example Settings
- Change the value of the Creation Time field.
- Move to another tab and back to the Example Settings. (Or Press OK to close, and reopen the settings again)
- Observe the Creation Time again shows the initial (default) value, NOT the manually entered value.

### Expected Result
The value entered by the user should be stored and usable by the underlying code.

### Actual Result
The value entered by the user is ignored, and the default value (or a programmatically changed value) is used.

### Other remarks
When using a DateTime field in our own plugins, we observe that the value entered by the user in the GUI does not get stored in the underlying variable. It is possible to change the underlying variable programmatically, and this will be reflected in the value shown by the GUI, but the value changed in the GUI never gets used.

**Comment by alnlarsen** [comment]
I see what you mean, this is a bit strange. This almost looks like an oversight to me. It happens because there is no `IStringValueAnnotation` implementation for `DateTime`, but there is one for `TimeSpan`. If we already support `TimeSpan`, I think we should support `DateTime` too.

**Comment by alnlarsen** [comment]
I have opened a PR with a proposed fix for this problem, but even if it is accepted it won't be included in a release for several months. 

If this is a feature you need immediately you can create your own `IAnnotator` implementation.
Here is a small example implementation for how you could add support for DateTime yourself:

```csharp
/// <summary>
/// This class defines how a DateTime value is converted to and from a string
/// </summary>
class DateTimeAnnotation : IStringValueAnnotation
{
    private AnnotationCollection annotation;
    public DateTimeAnnotation(AnnotationCollection annotation)
    {
        this.annotation = annotation;
    }
    public string Value
    {
        get
        {
            if (annotation?.Get<IObjectValueAnnotation>(from: this).Value is DateTime dt)
                return dt.ToString(CultureInfo.CurrentCulture);
            return "";
        }
        set
        {
            if (annotation == null) return;
            if (DateTime.TryParse(value, out var dt))
                annotation.Get<IObjectValueAnnotation>(from: this).Value = dt;
        }
    }
}

/// <summary>
/// This is an annotator. It is invoked by OpenTAP to annotate objects with data when `AnnotationCollection.Annotate` is called.
/// This is mostly used by GUIs to display data, and to define how data is written back into objects. 
/// </summary>
public class MyCustomAnnotator : IAnnotator
{
    public void Annotate(AnnotationCollection annotation)
    {
        // If this member is an instance of DateTime, we should add our DateTimeAnnotation to the annotation collection.
        // In this way, later invocations of 'annotation.Get<IStringValueAnnotation>()' will return this instance of our
        // DateTimeAnnotation, and the GUI will use our implementation to read/write dates.
        var mem = annotation?.Get<IMemberAnnotation>();
        if (mem?.ReflectionInfo?.DescendsTo(typeof(DateTime)) == true)
            annotation.Add(new DateTimeAnnotation(annotation));
    }

    public double Priority => 2;
}
```

We also have an example for implementing support for IP addresses in the SDK examples project:
https://github.com/opentap/opentap/blob/main/sdk/Examples/PluginDevelopment/GUI/IPAnnotation.cs

**Comment by bogdan-achim** [comment]
Verified in v9.24.0-rc.1
