### ISSUE TITLE
Wrong release name: 8.18.0 instead of 9.18.0

### ISSUE THREAD

**Issue by g-galante** [opentap/opentap#661]
Check the right sidebar on https://github.com/opentap/opentap
![image](https://user-images.githubusercontent.com/102026043/174019187-1f1bb0a3-be06-45bb-8217-34c94cbc7ad9.png)

and https://github.com/opentap/opentap/releases/tag/v9.18.0
![image](https://user-images.githubusercontent.com/102026043/174018774-ec51c5f8-a282-49ed-9df4-004e0c3aca43.png)

**Comment by alnlarsen** [comment]
@g-galante I don't see it, has this been fixed?

**Comment by sebastian-pop** [comment]
@alnlarsen @g-galante I fixed this
