### ISSUE TITLE
9.18.1: AssemblyData.SemanticVersion not correct

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#665]
The `AssemblyData.SemanticVersion` for `OpenTap.dll` and `OpenTap.Package.dll` in 9.18.1 return 9.18.0. It looks like the `SemanticVersion.TryParse` call in AssemblyData always fails because `RawVersion` is not actually set to a semantic-version compliant string.

**Comment by sebastian-pop** [comment]
Fixed. Verified on 9.18.2-rc.1

![image](https://user-images.githubusercontent.com/97734470/175031684-548c38d7-06b0-44bb-90c0-3523727f8acc.png)
