### ISSUE TITLE
Installing a package and ignoring to install its dependency will still install the package

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#67]
Originally filed May 07 2021 by Sebastian Vlaic on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/646)

**Environment:**

Windows 10, 64-bit

OpenTAP 9.14.-rc.1 (not reproduced on 9.11)

**Steps to reproduce:**

1. `tap package install "DMM Test Steps" -r "http://packages.opentap.keysight.com" -version 2.0`
2. Choose **Ignore** when asked to install dependency

**Actual result:**

"DMM Test Steps" is installed without it's dependency

![image](https://gitlab.com/OpenTAP/opentap/uploads/a6652871e9eee369e6159aadcef03430/image.png)

**Expected result:**

On 9.11 "DMM Test Steps" would not be installed

Is this an intended change?

![image](https://gitlab.com/OpenTAP/opentap/uploads/8275b7985b88adb3dcb8fb018ce741c8/image.png)

**Other remarks:**

**Comment by alnlarsen** [comment]
We no longer ask to install dependencies, so we can consider this fixed.
