### ISSUE TITLE
https://opentap.io/about still references the stale "Open Source in Test Automation v4" white paper

### ISSUE THREAD

**Issue by g-galante** [opentap/opentap#686]
@bdirenzo-keysight As already happened in the past for issue https://github.com/opentap/opentap/issues/489#issuecomment-1080805710, the new document version is not showing up yet: https://opentap.io/about still links to the old https://opentap.io/assets/whitepapers/Open-Source-in-Test-Automation-v4.pdf.
```
$ curl -I https://opentap.io/assets/whitepapers/Open-Source-in-Test-Automation-v4.pdf
HTTP/2 200 
server: nginx
date: Fri, 24 Jun 2022 08:50:27 GMT
content-type: application/pdf
content-length: 1335808
last-modified: Tue, 17 May 2022 21:22:03 GMT
etag: "628411fb-146200"
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
accept-ranges: bytes
```
But, with a little bit of name guessing, I can see that the updated document has already been uploaded (https://opentap.io/assets/whitepapers/Open-Source-in-Test-Automation-v5.pdf), and looks very good.
```
$ curl -I https://opentap.io/assets/whitepapers/Open-Source-in-Test-Automation-v5.pdf
HTTP/2 200 
server: nginx
date: Fri, 24 Jun 2022 08:50:37 GMT
content-type: application/pdf
content-length: 1336700
last-modified: Tue, 21 Jun 2022 12:13:23 GMT
etag: "62b1b5e3-14657c"
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
accept-ranges: bytes
```
Maybe the web page update just needs a little kick ;)

_Originally posted by @g-galante in https://github.com/opentap/opentap/issues/658#issuecomment-1165375697_

**Comment by bdirenzo-keysight** [comment]
@sebastian-pop are you able to look at this? Maybe just that link was missed.

**Comment by sebastian-pop** [comment]
Good find. I have updated the link
