### ISSUE TITLE
SDK: Require "Version" field for packages

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#691]
There are a ton of build problems occurring when packages are updated because we allow people to omit the `Version` field in `<AdditionalOpenTapPackages ../>` and `<OpenTapPackageReference ../>`.

I propose a source breaking change so we require the version field to be set. Whether `Any` should be allowed is debatable.

I call this source breaking because plugins will continue to build and function as usual until the user manually upgrades the NuGet reference to a newer version which has this requirement.

NuGet doesn't allow omitting versions. In fact, NuGet doesn't even allow version specifiers, but requires exact versions, but I think we still want version specifiers. Now I can see why they made that decision.

If this is implemented, the error messages should be very helpful to support the develoepr in a smooth migration. Exact line numbers where the versions need to be added, and maybe even a suggested version string if possible.

**Comment by alnlarsen** [comment]
This was not an issue before 9.17 when we completely changed the behavior of our dependency resolver, but it is a pretty serious issue now. 

This is related to #460. Fixing #460 would kind of fix this issue, but I still think omitting the Version field is a terrible idea.

**Comment by rmadsen-ks** [comment]
We expect to find a proper solution to #460 and so there will be no need for this.

You could say that specifying the version provides more reproducible builds, but that is up to the user.
