### ISSUE TITLE
JWT Token improvements

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#696]
9.18.0 added new jwt token APIs (AuthenticationSettings and TokenInfo classes). Some improvements would be good here:

* JWT tokens should be decoded using base64-url instead of regular base64
* All claims should be accessible in the API, not only "azp" and "iss" (most important claim is probably "sub" which is not accessible at all)
* TokenInfo should represent data in the token, and not make assumptions about a refresh slack
* Use "exp" claim as source of "TokenInfo.Expiration" instead of "expires_in" field in response (not all tokens come from a response like this, and the "exp" should be more reliable since it is signed)
* access token and its corresponding refresh token should be kept together in AuthenticationSettings.

**Comment by Denrask** [comment]
We need to use "exp" also because that's an actual datetime (or seconds since unix epoch) so it can be serialized to XML and back and the expiry is still valid.
