### ISSUE TITLE
'tap package create' packages dependencies from ignored folders

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#70]
Originally filed May 25 2021 by Alexander Nørskov Larsen on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/661)

A folder containing a ".OpenTapIgnore" file should not be considered when resolving dependencies during "tap package create"

**Comment by rmadsen-ks** [comment]
This is hard to reproduce and is a low value fix. We wont fix this unless the problem reappears.
