### ISSUE TITLE
CSV Parameters throws exception while running through OpenTap CLI

### ISSUE THREAD

**Issue by amkhurana** [opentap/opentap#727]
**Describe the bug**

**Environment (please complete the following information):**

 - OS: [Windows 10]
 - OpenTAP Version [9.18.4]

**To Reproduce**

1. Create a Package or paste package in a specified path so that tappackage accessible.

2.  Install Tap Package so that CLI can access Package

3. Create CSV file for passing input parameters.

4. Try to run "Tap run -v --list-external-parameters Sample1.csv 

**Actual behavior**

**Expected behavior**

**Additional context**

Add any other context about the problem here. Please also attach a log file from <InstallDir>\SessionLogs\ that shows the issue when possible/relevant.
![69691c6f-3c1b-4580-8c6e-46ad90081812](https://user-images.githubusercontent.com/54167657/182112406-0d26f85c-0dd2-48c8-80a7-930e29a42b52.jpg)

**Actual behavior**

An xml exception occurs which says that "Data at root element is invalid"

**Expected behavior**

It should allow to execute test step while taking inputs from csv file

**Additional context**

Add any other context about the problem here. Please also attach a log file from <InstallDir>\SessionLogs\ that shows the issue when possible/relevant.
![f5819397-af4a-4f0f-b493-ba5eee748ed7](https://user-images.githubusercontent.com/54167657/182112830-79dd925d-7237-49f5-9622-c689b006a407.jpg)

**Comment by rmadsen-ks** [comment]
Maybe what you want is to 'load' external parameters from a CSV file. In this case the `-e` argument should be used.

The behavior seems to be as expected. Closing this for now.
