### ISSUE TITLE
Repeat step behavior change

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#729]
We changed the verdict clearing behavior of `Repeat` at some point between 9.14 and 9.17.

Below is an example of a step which gives an `Error` verdict the first two times, and a pass verdict the third time.

In OpenTAP 9.14.0, the plan would succeed because the `Repeat` step would clear the verdict. In 9.17, the verdict is not cleared, so the `Error` verdict is used.

I only observed this discrepancy while overriding `Break Conditions` to None. See screenshot

![image](https://user-images.githubusercontent.com/95965749/182547351-728c8430-66de-45cc-95c6-72bca80a7475.png)

**Comment by alnlarsen** [comment]
Under the circumstances where this discrepancy arises it seems to me that this was a bug in 9.14. 

Since 9.17, we have had the `ClearVerdict` property which controls whether or not verdicts should be cleared between runs. 

`Retry` also causes the verdict to be cleared only in cases where a break condition was triggered, which I think is fine.

Fixing this discrepancy would mean clearing the verdict in some circumstances where no break condition was triggered, and where `ClearVerdict` was explicitly set to false, which to me sounds even worse than the current discrepancy with OpenTAP 9.14.0.

**Comment by rmadsen-ks** [comment]
It seems like this is the behavior we intend so this wont be fixed.
