### ISSUE TITLE
"tap package list --os" should show an error with an invalid argument

### ISSUE THREAD

**Issue by apantir** [opentap/opentap#732]
**Environment (please complete the following information):**
OS: macOS x64 with version 12.5
OpenTAP version 9.18.4+7dec4717

**To Reproduce**

1. Access the Terminal
2. Go to .tap folder
3. Use command ./tap package list --os test
4. You should get a list with installed apps on the local machine
5. Use command ./tap package list --os 443fdfs
6. You should get a list with installed apps on the local machine
7. Use command ./tap package list -i
8. You should get the same results as above
9. A clear and concise description of what the bug is.

**Actual behavior**

You get the same results from a wrong command when using **--os** in front and any random numbers or letters after

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/110477118/182628120-9de7ab38-4f47-46dd-bced-69e5c5f044de.png)

**Expected behavior**

Since the argument for **--os** is invalid, running this command should show an error

**Comment by rmadsen-ks** [comment]
`--os` is valid in this context. If you specify an OS name that does not exist it should just return an empty list.

It should also apply the argument to installed packages however.
