### ISSUE TITLE
<Package.Dependencies> element is included when serializing `PackageVersion[]`

### ISSUE THREAD

**Issue by alnlarsen** [opentap/opentap#739]
`<Package.Dependencies>` is a concept which only makes sense for test plans, but we include it in other instances, such as when serializing `PackageVersion[]`. This is annoying because it will add a dependency on the currently used version of OpenTAP in order to deserialize a data object, which will cause serializer errors when trying to deserialize that same string in an older version of OpenTAP.

Let's fix this :)

**Comment by rmadsen-ks** [comment]
This is not entirely right, we also need Package.Dependencies for at least component settings, but I am not sure what else.

**Comment by alnlarsen** [comment]
I agree that it makes sense in other contexts than test plans. 

There are many contexts where it does not make sense, such as when using TapSerializer as a generic serializer for serializing e.g. a `PackageIdentifier`. We already have a hardcoded workaround specifically for `PackageDef` and `PackageIdentifier`. I propose adding `PackageVersion` to this hardcoded workaround.
