### ISSUE TITLE
TestStep Version in a TestPlan get the wrong format

### ISSUE THREAD

**Issue by StefanHolst** [opentap/opentap#749]
**Describe the bug**

TestStep Version in a testplan get the wrong format: `<TestStep type="WebApiTester.RequestStep" Version="0.3.0.0"`

**Environment (please complete the following information):**

 - OS: MacOS
 - OpenTAP Version: 9.18.4

**To Reproduce**

Save a testplan with teststeps from WebApiTester using the TUI:
```
OpenTAP      - 9.18.4+7dec4717         - installed
TUI          - 0.1.0-beta.150+1428669d - installed
WebApiTester - 0.3.0-beta.9+049da19e   - installed
```

**Actual behavior**

TestStep version gets a wrong version format with 4 numeric version fields.

**Expected behavior**

That it uses a semantic version format.

**Additional context**

Cannot be reproduced in the latest opentap beta

**Comment by rmadsen-ks** [comment]
We should check this for 9.18.5 as well.

**Comment by alnlarsen** [comment]
We no longer serialize the test step version since #588 

@rmadsen-ks can we just close this?

**Comment by rmadsen-ks** [comment]
Yes! lets close it.
