### ISSUE TITLE
Resources are Opened after LicenseException

### ISSUE THREAD

**Issue by witoldpiet** [opentap/opentap#751]
It looks as if OpenTAP opens resources used by a test plan after a LicenseException has been thrown. The exception will cause that the test plan will not be executed so no reason to open the resources.

**Comment by sebastian-pop** [comment]
The issue can be reproduced by having a counted license and running the same test plan at the same time:

The test plan contains a Charge step from Demonstration configured to use instrument PSU

![image](https://user-images.githubusercontent.com/97734470/184870090-bb578541-ade8-4b7b-9dd8-791ce3210d75.png)
[SessionLog 2022-08-16 04-28-34.txt](https://github.com/opentap/opentap/files/9350543/SessionLog.2022-08-16.04-28-34.txt)
