### ISSUE TITLE
CLI options with [Browsable(false)] are visible

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#755]
**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.18.4

**To Reproduce**

1. Run `tap package list -h` - > the option `--no-isolation` is visible

2. Run `tap package check-updates -h` -> the option '--startup' is visible

**Actual behavior**

These options have [Browsable(false)] attribute and are visible

**Expected behavior**

CLI options with [Browsable(false)] attribute should be hidden

![image](https://user-images.githubusercontent.com/97734470/184340789-31e15947-888f-4c71-aa43-30814c02f238.png)

![image](https://user-images.githubusercontent.com/97734470/184340846-427bc284-9548-4fba-b069-5911212b93cd.png)

**Comment by rmadsen-ks** [comment]
This was not originally intended to depend on Browsable(false), but instead  `CommandLineArgumentAttribute.IsVisible`:
```
        /// <summary>
        /// Indicates whether this will be shown when writing CLI usage information.
        /// </summary>
        public bool Visible { get; set; }
```

I guess we should obsolete 'Visible' in favor of `Browsable(false)`, since that is the more OpenTap-way to do it.
