### ISSUE TITLE
REST-API 2.9.1 does not show up in Package Manager UI when OpenTAP 9.18.4 is installed

### ISSUE THREAD

**Issue by alan-copeland-keysight** [opentap/opentap#761]
Using Editor CE...

packages.opentap.io and the cli (tap package list) both show the package. I had to go enable "show incompatible packages" for it to show up.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/69871845/184461491-2f991d4c-43cc-4674-aa11-c3661e3ed6cf.png">

My guess is that this is because there is a newer REST-API beta package that relies on TAP ^9.19. So, the filter logic is wrong when considering what should be shown or not.

**Comment by alnlarsen** [comment]
I can reproduce this. It is a bug in the package manager GUI, and is not related to OpenTAP.

**Comment by alnlarsen** [comment]
This will be fixed in KS8400. Closing this.

**Comment by sebastian-pop** [comment]
Fix is confirmed on KS8400 9.19.0-beta.13.
