### ISSUE TITLE
Caught error while finishing serialization: Failed cloning NotSet as OpenTap.Input`1

### ISSUE THREAD

**Issue by lay-kim** [opentap/opentap#763]
**Environment (please complete the following information):**

 - OS: Windows 10, 64-bit
 - OpenTAP Version 9.18.4
**To Reproduce**

1. Add a Test Plan Reference step
2. Load [Flow.TapPlan](/uploads/1fbbae4dd573b6eb20a64fc88cd2085d/Flow.TapPlan)
3. Click Load again

**Actual behavior**

![image](https://user-images.githubusercontent.com/100328077/185537550-2b1d3ec7-ae64-4c8c-a4b5-2ac67761acb4.png)

**Comment by rmadsen-ks** [comment]
Hi @lay-kim, 
Thanks for submitting an issue.

It seems I cannot access your uploaded test plan file. Can you describe how to create it?

**Comment by lay-kim** [comment]
Hi @rmadsen-ks , 
I have reattached the test plan. Please change the extension to `.TapPlan` after downloading.
[Flow.zip](https://github.com/opentap/opentap/files/9448705/Flow.zip)
