### ISSUE TITLE
add sweep values from file

### ISSUE THREAD

**Issue by bdirenzo-keysight** [opentap/opentap#786]
Right now, Sweep  values can only be manually loaded from a file with the Edit window, but they can't be combined with other Test Plan Parameters. Ideally this can be exposed some how (either parameterizing the Loaded file itself or the lower level table)   
![image](https://user-images.githubusercontent.com/78063177/188760322-bc7e8fbd-03fd-4ad7-b9bb-a5d40a1242db.png)

**Comment by bdirenzo-keysight** [comment]
One reason users want this exposed at a higher level (other than the complexity of multiple layers of parameters) is that locking the Test Plan prevents the Sweep Values from being changed.

**Comment by bdirenzo-keysight** [comment]
@rmadsen-ks, @AsgerIversen we will need to prioritize this for the next release. I believe overlaps or maybe is the same as #77.

**Comment by rmadsen-ks** [comment]
A small improvement that is easier to implement is add sweeping from a file, instead of the list. Then the file path can be parameterized.

Otherwise, the general feature request is very complicated to fix.

**Comment by alnlarsen** [comment]
@bdirenzo-keysight is this still something you need? I have some issues with the implementation in the linked pull request. If this is a requirement for the 9.20 release, we need to get aligned asap as feature freeze is coming up on Feb 9.

**Comment by rmadsen-ks** [comment]
This has been fixed in the most recent version of the CSV plugin.
