### ISSUE TITLE
Behavior change with old plugins 9.19 vs 9.18

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#808]
**Describe the bug**

9.18 would install a plugin missing a dependency with `-f` but 9.19 will not

I am reporting this as a behavior change, not sure if this is a bug or a feature

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.19.0-rc1

**To Reproduce**

1. `tap package install RemoteSigntool -r "http://packages.opentap.keysight.com" -f`

**Actual behavior**

on **9.19.0-rc.1**, the plugin is not installed. Log [SessionLog 2022-09-14 00-27-07.txt](https://github.com/opentap/opentap/files/9563842/SessionLog.2022-09-14.00-27-07.txt). Note: It will be installed if `--version any` is specified

![image](https://user-images.githubusercontent.com/97734470/190090867-76325601-e031-4573-825a-be03165a9064.png)

on **9.18.5**, the plugin is installed. Log [SessionLog 2022-09-14 00-27-22.txt](https://github.com/opentap/opentap/files/9563853/SessionLog.2022-09-14.00-27-22.txt)

![image](https://user-images.githubusercontent.com/97734470/190091294-84eb09b0-25f1-42ca-8f68-b53cc7d90dc4.png)

**Comment by alnlarsen** [comment]
I can reproduce this. It works if I use "--version any". I only did this on Linux. @sebastian-pop can you check if this is also the case on Windows?

**Comment by jfaaborg** [comment]
@rmadsen-ks will check why the behaviour is like this

**Comment by sebastian-pop** [comment]
@alnlarsen I can confirm on WIndows

![image](https://user-images.githubusercontent.com/97734470/190621191-86f8a5ad-4e9b-4580-8732-e6bb3bf3cbf1.png)

**Comment by sebastian-pop** [comment]
Fixed. Verified on 9.19.0-rc.3

![image](https://user-images.githubusercontent.com/97734470/190644303-628d80e0-b5cc-4053-89c5-4a98d5f5ae28.png)
