### ISSUE TITLE
`tap package list` on macOS shows all packages on the repo

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#817]
**Environment (please complete the following information):**

 - OS:  macOS
 - OpenTAP Version 9.19.0-beta.54

**To Reproduce**

1. Run `tap package list`

**Actual behavior**

All packages are displayed. Log:  [SessionLog 2022-09-14 14-06-54.txt](https://github.com/opentap/opentap/files/9566222/SessionLog.2022-09-14.14-06-54.txt)

**Expected behavior**

Only macOS-compatible packages should be displayed

**Additional context**

**Comment by rmadsen-ks** [comment]
It seems like it show Linux and MacOS compatible packages. It does not display windows packages.

**Comment by jfaaborg** [comment]
We will look at this in 9.20, mac is not officially supported yet.,

**Comment by alnlarsen** [comment]
In the majority of cases, a Linux compatible package will be MacOS compatible. While it would technically be more correct to only show MacOS packages, I'm not sure if that is actually the best user experience.

**Comment by Razvan-Muresan** [comment]
Verified using OpenTAP version 9.22.0-rc.1+76235bea
