### ISSUE TITLE
tap package install Any Release / Any does not resolve to the expected packages

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#824]
Currently the meaning of Any Release, means a compatible version specifier. This means that it actually looks for the oldest version of the package.

So "tap package install OpenTAP" installs the oldest OpenTAP compatible with what you otherwise have in the installation.

```
./tap image install "REST-API:2.6,OpenTAP" --dry-run
Resolved packages:
   Keysight Floating Licensing:    1.0.44+8197912e
   OpenTAP:    9.16.0+6cab4b01
   REST-API:    2.6.3+4b18b59f
```
Where as we expected the following:
```
Resolved packages:
   Keysight Floating Licensing:    1.0.44+8197912e
   OpenTAP:    9.18.5+0328e9b4   (Newest Release)
   REST-API:    2.6.3+4b18b59f
```

**Comment by sebastian-pop** [comment]
Fixed. Verified on OpenTAP 9.19.0-rc.3
