### ISSUE TITLE
tap package install cannot properly resolve "any" versions

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#825]
When beta versions exists, `tap package install --version any` cannot resolve the package.

This is because of an optimization that limits the number of requests to the package repository api by looking at the PackageDependencySpecifier version pre-release, but not whether the AnyPreRelease flag has been set.

**Comment by sebastian-pop** [comment]
Fixed. Verified on 9.19.0-rc.3

![image](https://user-images.githubusercontent.com/97734470/190643845-a11e996f-d498-40f2-9d85-8d3e7557920c.png)
