### ISSUE TITLE
Having a package in cache changes the order in `tap package list`

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#828]
**Describe the bug**

**Environment (please complete the following information):**

 - OS:  Windows 10
 - OpenTAP Version 9.19.0-beta.54

**To Reproduce**

1. Have Editor X version 1.2.0 in the cache
2. `tap package list "Editor X" --os Windows --r https://packages.opentap.keysight.com -r http://packages.opentap.io` - > version 1.2.0 is at the top even though there is a newer 1.4.0 version
3. Delete Editor X 1.2.0 from cache
4. Run the same list command again - > 1.4.0 is at the top

**Actual behavior**

![image](https://user-images.githubusercontent.com/97734470/190574951-bb20b5cd-e610-4031-88fe-a862bc68b8aa.png)

**Expected behavior**

Having a package in cache should not change the order in the list

**Comment by jfaaborg** [comment]
We should sort the order and show the latest first.

**Comment by sebastian-pop** [comment]
Fixed. also the list is now ascending. Nice. OpenTAP 9.19.0-rc.3

![image](https://user-images.githubusercontent.com/97734470/190644572-f80fe500-1e95-4d27-a846-d11207931671.png)
