### ISSUE TITLE
Incorrect `Editor X` version resolved. Depends on cache

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#829]
**Describe the bug**

It's installing an older release instead of the latest

**Environment (please complete the following information):**

 - OS: [e.g. Windows 10]
 - OpenTAP Version [e.g. 9.17.0]

**To Reproduce**

1.  Install Editor X 1.2.0 `tap package install "Editor X" --version 1.2.0 -r https://packages.opentap.keysight.com -r http://packages.opentap.io`
2. Uninstall everything `tap package uninstall "Keysight Floating Licensing" "REST-API" "Editor X"`
3. Verify which is the latest Editor X release `tap package list "Editor X" -r https://packages.opentap.keysight.com -r http://packages.opentap.io` - > version 1.4.0 is the latest
4. Install the latest release of Editor X '`tap package install "Editor X"  -r https://packages.opentap.keysight.com -r http://packages.opentap.io`'

**Actual behavior**

Version 1.2.0

**Expected behavior**

Version 1.4.0 should be installed

Running `tap package install "Editor X" --version 1.4.0 -r https://packages.opentap.keysight.com -r http://packages.opentap.io` will correctly install Editor X 1.4.0

**Comment by rmadsen-ks** [comment]
This was fixed by #823

**Comment by sebastian-pop** [comment]
Fixed. Verified on 9.19.0-rc.3
