### ISSUE TITLE
System-wide packages also install the minimum OpenTAP version in ProgramData

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#830]
**Describe the bug**

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.19.0-beta.54

**To Reproduce**

1. `tap package install "PathWave License Manager Minimal"`

**Actual behavior**

Message of duplicate installations:

![image](https://user-images.githubusercontent.com/97734470/190586783-eed052d1-cb85-43ba-843f-6cc0bf764cea.png)

In `C:\ProgramData\Keysight\Test Automation\Packages\OpenTAP` there is OpenTAP version 9.11.0 installed

**Expected behavior**

Should OpenTAP be installed in ProgramData? this was not happening on 9.18

**Comment by rmadsen-ks** [comment]
OpenTAP should not be installed there. That is an error caused by no longer supporting the --no-dependencies argument.

**Comment by sebastian-pop** [comment]
Fixed. Verified on 9.19.0-rc.3
