### ISSUE TITLE
SessionLogs/Latest

### ISSUE THREAD

**Issue by frederikja163** [opentap/opentap#846]
Currently tap creates a sessionlog every time it starts up, but the newest sessionlog always has a new name, making it harder than necessary to find it. I suggest we make either a symlink og a hardlink to the lattest sessionlog and save it in a SessionLog/Latest.txt file, so the latest session log is always easy to find.

**Comment by rmadsen-ks** [comment]
I like this idea!

**Comment by bogdan-achim** [comment]
Should this change also be reflected on Windows?

**Comment by bogdan-achim** [comment]
Tested and confirmed on Linux on v9.21.0-beta.10
