### ISSUE TITLE
Dockerfile Base image is Focal , but Docker Image tag is Bionic

### ISSUE THREAD

**Issue by darwinsubramaniam** [opentap/opentap#850]
**Describe the Question**
Not sure if this is a bug , would like to make this as part of question 
This question regarding the docker image tag available in Docker hub
https://hub.docker.com/r/opentapio/opentap/tags 

Based on the [Dockerfile](https://github.com/opentap/opentap/blob/main/docker/Linux/Dockerfile) from this repo , it seems to be using focal image of dotnet, so but why is the OpenTAP image is tagged to bionic? 

https://github.com/opentap/opentap/blob/66c84c6268b72ace8fdea8f1760fea6f50f6054c/docker/Linux/Dockerfile#L33

Is there anything I have missed?

**Comment by darwinsubramaniam** [comment]
https://github.com/opentap/opentap/blob/66c84c6268b72ace8fdea8f1760fea6f50f6054c/.github/workflows/ci.yml#L839

bionic is hardcoded into the build process.

**Comment by rmadsen-ks** [comment]
@AsgerIversen, do you know what is going on here?

**Comment by darwinsubramaniam** [comment]
Hi @AsgerIversen ,

Based of from the docker image publish in Dockerhub, , it should have been Ubuntu Focal (20.04)  right ?
