### ISSUE TITLE
Add support for PyVISA-py

### ISSUE THREAD

**Issue by bdirenzo-keysight** [opentap/opentap#863]
For other platforms and for python we should support pyVISA-py as one of the VISA options.

**Comment by bdirenzo-keysight** [comment]
I think we can do this with some minor OpenTAP changes + a plugin

**Comment by alan-copeland-keysight** [comment]
Initial prototype!

In testing it works on Mac x64 and Windows x64, sending VISA traffic for the SCPI Step and DMM plugin (_without any changes to those 2 plugins_). The code is broken up into 2 parts:

- Pluggable VISA in OpenTAP (_Visa.cs_):
  * https://github.com/alan-copeland-keysight/opentap/tree/feature/make-visa-pluggable
  * Summary:
    * Defines an IVisa interface to make interop between C# and Python work
    * Create a setting that specifies the class name for  the VISA implementation
      * By default this just uses the current tap behavior 
      * Maybe this eventually has other settings in it, like "What is the pyvisa backend? Keysight/NI/Tek/R&S, not just @py"
- pyvisa/pyvisa-py wrapper using the Python 3.0.0-rc plugin 
  * https://github.com/alan-copeland-keysight/PythonVisa
  * Summary:
    * Implements IVisa interface:
    * Fills in some functionality gaps in the underlying pyvisa-py library (_e.g. resource class attribute is not implemented_)

**Comment by alnlarsen** [comment]
PR: https://github.com/opentap/opentap/pull/932
