### ISSUE TITLE
Parameterized `Verdict Of` is a field not a dropdown

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#900]
**Environment:**

Windows 10, 64-bit

Test Automation 9.19.0-rc.2 (9.18.4 reproduced)

**Steps to reproduce:**

1. Add an If Verdict step
2. Select something in Verdict Of
3. Parameterize Verdict of
4. Verify parameter

**Actual result:**

Verdict of setting is a dropdown

Verdict of parameter is a field

![image](https://user-images.githubusercontent.com/97734470/198976851-12d7a0b1-46c9-49e7-a62b-a0465c420cf2.png)

**Expected result:**

**Other remarks:**

**Comment by alnlarsen** [comment]
I poked a bit at this:

1. It works correctly when parameterizing on a parent
2. Also on the parent's parent
3. It does **not** work when parameterizing on the test plan
4. Parameterizing on the test plan, and loading the test plan as a reference **DOES** work correctly.

We should figure out why the testplan settings behave different from the other scenarios.
