### ISSUE TITLE
Add iteration functionality to SweepParameterRangeStep

### ISSUE THREAD

**Issue by tom-mun** [opentap/opentap#902]
SweepParameterStep contains a parameter IterationInfo with the current iteration number, as well as the total number of iterations the step will run. I can't find a parameter with the same functionality in SweepParameterRangeStep, and it would be nice to have

**Comment by cpetku** [comment]
I had the same concern and addressed it like this.  I believe the output attribute is applicable to other looping steps when accessing the iteration variable...

[patch.txt](https://github.com/opentap/opentap/files/10060385/patch.txt)
