### ISSUE TITLE
Uninstall package: 'Unable to delete .dll" message 

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#915]
**Describe the bug**

Unable to delete messages when uninstalling package

**Environment (please complete the following information):**

 - Windows 10 64bit
 - OpenTAP Version  9.19.4-rc.1 (reproduced 9.19.3)

**To Reproduce**

1. Clean install OpenTAP using the installer
2. 'tap package install HTML5'
3. 'tap package uninstall HTML5'

**Actual behavior**

Package is uninstalled but messages in log 'Unable to delete'

Log: [SessionLog 2022-11-16 10-18-41.txt](https://github.com/opentap/opentap/files/10019542/SessionLog.2022-11-16.10-18-41.txt)

![image](https://user-images.githubusercontent.com/97734470/202126613-8b0902d5-516d-4717-8eab-a6a9e18c24f9.png)

**Comment by rmadsen-ks** [comment]
I can reproduce this. In the end, it seems it is able to delete the file, but always after 10 retries.

**Comment by rmadsen-ks** [comment]
This error occurs because HTML5 lists the file System.Runtime.CompilerServices.Unsafe.dll twice. So on the second try, delete throws an exception because the directory does not exist.

**Comment by sebastian-pop** [comment]
Confirmed as fixed on 9.19.4-beta.4
