### ISSUE TITLE
Only show the "Updates available for" once per CLI command

### ISSUE THREAD

**Issue by jfaaborg** [opentap/opentap#919]
It seems strange that the user get's notified about updates twice when using the CLI.

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/93329857/202484791-0e13e0d3-52b5-4351-8ef4-1f306853d3ba.png)

**Comment by alnlarsen** [comment]
I think this happens because the isolated sub process also performs an update check. It should be simple to disable the check in the subprocess.

**Comment by rmadsen-ks** [comment]
We have introduced code which disables this for the child process, but this was done already in 2021, so the question is why this shows up in this case.

**Comment by rmadsen-ks** [comment]
.. In addition to that we have introduced a delay of 3 seconds so if the application ends before then, there will be no update check.

**Comment by rmadsen-ks** [comment]
I think we can close this since its probably not an issue anymore.
