### ISSUE TITLE
Set MacroString.Context on deserialization

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#931]
it seems that while MacroString.Context is set during object construction, it is not set when the object gets deserialized, forcing people to do something like this:

```cs
    MacroString filepath = new MacroString(){Text = "123"};
    public MacroString Filepath{
          get => filepath;
          set {
                  filepath = value;
                  filepath.Context = this;

          }
   }
```
instead, MacroString.Context should be set to the target object current MacroString.Context value.

**Comment by alnlarsen** [comment]
I am unable to reproduce this, but I have created a unittest that verifies the correct behavior: #986 

Rolf, can you provide some more information about how to trigger this issue?
