### ISSUE TITLE
Sweep Parameter is Iterating Through Invalid Values

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#95]
Originally filed September 28 2021 by Vlad Opris on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/762)

**Environment:**

Windows 10, 64-bit

OpenTAP 9.16.0-beta.29

**Steps to reproduce:**

1. Add a Sweep Parameter step and a Delay child to the Test Plan.
2. Parameterize Time Delay on Parent.
3. Select Sweep Parameter and Edit Sweep Values.
4. Add 2 rows to the Data Grid.
5. Set the first Time Delay to -1.
6. Set the second Time Delay to 3.
7. Run the Test Plan.

**Actual result:**

Test Plan is completed with an Error Verdict, but the invalid Time Delay has been run with a value of 3 s (second iteration value).

[SessionLog_2021-09-27_09-13-58.txt](https://gitlab.com/OpenTAP/opentap/uploads/4c7fe778de3bf66e3f28b3ee6510e5ba/SessionLog_2021-09-27_09-13-58.txt)

**Expected result:**

Test Plan execution stops after throwing the error.

**Comment by rmadsen-ks** [comment]
DelayStep uses an exception to avoid setting the property to an invalid value. We should break iteration if a property setter throws an exception.
