### ISSUE TITLE
Allow opt in to result table optimization

### ISSUE THREAD

**Issue by rmadsen-ks** [opentap/opentap#956]
A few have had issues with the table collapsing feature, which for the same test step, if the result tables are compatible, will combine multiple result tables into one.

Note, that this only happens if the tables has the same name, parameters, columns, etc. - they need to be 100% compatible.

However, still the expectation from an API point of view is sometimes that one PublishResult call will result in one OnResultsPublished call. 

I suggest we introduce an IResultListenerRequestCollapseTables API, which allows the developer to opt in to the new behavior. In this way we avoid breaking existing implementations which strongly relied on the previous behavior.

Opting in will cause slowdowns for some result listener types for some scenarios.

**Comment by Denrask** [comment]
@rmadsen-ks if a customer is waiting for this, please put it in current milestone. Until then, I'll put it in backlog.

**Comment by rmadsen-ks** [comment]
This is supported by making the result listener with the ```IMergedTableResultListener```interface.
