### ISSUE TITLE
*CLS / *RST erroneously setting viRead after command (incorrectly using ScpiQuery instead of ScpiCommand)

### ISSUE THREAD

**Issue by alan-copeland-keysight** [opentap/opentap#976]
The issue was introduced in this PR (Scpi Instrument Virtual Methods):

*CLS and *RST should use ScpiCommand, not ScpiQuery

https://github.com/opentap/opentap/pull/895

**Comment by alan-copeland-keysight** [comment]
@rmadsen-ks / @alnlarsen / @AsgerIversen / @bdirenzo-keysight - this would break all SCPI I/O in 9.20 if not fixed.

**Comment by rmadsen-ks** [comment]
@alan-copeland-keysight, can you verify PR #977?

**Comment by alan-copeland-keysight** [comment]
Sure, I'll check it

**Comment by alan-copeland-keysight** [comment]
Original issue shows the error like this (version 9.20.0-beta.7) with a *IDN? Test Plan:

![image](https://user-images.githubusercontent.com/69871845/214151513-e80cf709-4f01-40b3-90e5-869a242bb1d4.png)
