### ISSUE TITLE
USB SCPI instruments do not work on Ubuntu

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#996]
**Describe the bug**

The issue is **only for USB** instruments

- USB SCPI instruments do not work on Ubuntu
- Etherned based SCPI instruments work on Ubuntu

**Environment (please complete the following information):**

 - OS: Ubuntu 20.04
 - OpenTAP Version 9.19.4

**To Reproduce**

1. Using a DMM instrument 34405A
2. IO Libraries installed
3. Connection Expert:  Confirm `*IDN?` query works
4. Install TUI
5. Add a SCPI instrument using VISA from Connection expert
6. Add a SCPI step
7. Run it

**Actual behavior**

Error, resource not found. Log: 
[SessionLog 2023-01-31 18-08-41.txt](https://github.com/opentap/opentap/files/10548488/SessionLog.2023-01-31.18-08-41.txt)

**Expected behavior**

**Additional context**

![image](https://user-images.githubusercontent.com/97734470/215817702-6a9bbcb9-cd04-4cc3-b77b-4708e55585d1.png)

**Comment by jfaaborg** [comment]
@sebastian-pop, my understanding is that we think this case is somehow instrument specific. Let us know when you have done further testing.

**Comment by Denrask** [comment]
@sebastian-pop any updates on this?

**Comment by sebastian-pop** [comment]
Works on Ubuntu 20.04 with KS8500 1.5.0-rc. Thanks to @alan-copeland-keysight for validating
