### ISSUE TITLE
Multiple step edit: `If Verdict` step: Step setting `If` is not updated

### ISSUE THREAD

**Issue by sebastian-pop** [opentap/opentap#997]
**Describe the bug**

When editing multiple steps at the same time, the step setting `If` is not updated for all selected steps

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version  9.19.4

**To Reproduce**

1. Add two If Verdict steps and a Dialog step
2. Select both If Verdict steps
3. Set `If` to the verdict from Dialog

**Actual behavior**

Only one If Verdict step has been updated 

**Expected behavior**

Both If Verdict steps should be updated

**Additional context**

Reproduced with both KS8400 (https://gitlab.it.keysight.com/tap/tap/issues/6627) and Editor X (https://gitlab.it.keysight.com/tap/editors/editor-x/issues/563)

Also reproduced for Repeat step: the step setting `Verdict Of`

**Comment by alnlarsen** [comment]
@lay-kim I am unable to reproduce it with OpenTAP 9.20.0-rc.2 in Editor version 9.19.1. What steps did you take to reproduce it?

**Comment by lay-kim** [comment]
Hi @alnlarsen , I reproduce with the `Repeat` test step.

![Uploading repeat-verdict.gif…]()

**Comment by alnlarsen** [comment]
Okay, thanks!

**Comment by bogdan-achim** [comment]
Verified as fixed on EditorX v1.5.0-rc.2 & OpenTAP v9.20.0-beta.48+214e53ec

![997_fix_if_verdict_dialog](https://user-images.githubusercontent.com/118886454/224031233-d1be56f2-33c7-4d05-ac6a-61ca673970ba.gif)
